export interface AdminDashboardMetrics {
  newProspects30d: number;
  openOpportunities: number;
  opportunitiesByStage: Record<string, number>;
  conversionRate: number;
  activeCompanies: number;
  activeAgreements: number;
  contractsPendingSignature: number;
  contractsNearingExpiration: number;
  activeContracts: number;
  expiredContracts: number;
  commercialActivities30d: number;
  leadsWithoutFollowUp: number;
  opportunitiesWon: number;
  opportunitiesLost: number;
  recaudoDiarioCents: number;
  recaudoMensualCents: number;
  pagosAprobados: number;
  pagosPendientes: number;
  pagosRechazados: number;
  tasaAprobacion: number;
  obligacionesPendientes: number;
  obligacionesVencidas: number;
  reconciliationDifferencesOpen: number;
  openPqrCases: number;
  overduePqrCases: number;
  openDataSubjectRequests: number;
  overdueDataSubjectRequests: number;
  pendingApprovalGates: number;
}
