/**
 * Provider-agnostic payment interface (US-022 acceptance criteria -
 * method names copied verbatim: createPayment, getPaymentStatus,
 * validateNotification, optional createRefund). No Bold-specific
 * shape leaks through here - callers (a future PaymentOrdersService,
 * US-023+) depend only on this interface, never on BoldPaymentProvider
 * directly, so a future non-Bold provider can be swapped in via the
 * PAYMENT_PROVIDER token without touching consumers.
 *
 * Every field below is either literally named in the AC's own
 * documented Bold request/response shapes, or deliberately left as an
 * opaque `raw` passthrough where the exact shape isn't confirmed - see
 * each DTO's own comment.
 */

export interface CreatePaymentInput {
  /** Maps to Bold's reference_id - must be the safe, non-sequential
   * publicReference already generated by the payment-order domain
   * (US-023+), never a raw internal id. */
  publicReference: string;
  amountCents: number;
  currency: string;
}

export interface CreatePaymentResult {
  /** Bold's own status for this resource - raw, unmapped (see
   * bold-status.ts; internal status mapping is a later story). */
  status: string;
  /** The full, untouched provider response - persisted as-is into
   * PaymentTransaction.rawResponse (US-021), never trusted beyond the
   * confirmed `status` field above. */
  raw: unknown;
}

export interface PaymentStatusResult {
  status: string;
  raw: unknown;
}

export interface ValidateNotificationInput {
  payload: unknown;
  headers: Record<string, string | string[] | undefined>;
}

export interface ValidateNotificationResult {
  /** Always false in Phase 1: Bold's webhook signature header format
   * isn't confirmed from public docs (PRD openQuestions - "webhook-
   * specific page returned 404"). Never treat this as a verified event;
   * a later story stores it for reconciliation without letting it alone
   * drive an APPROVED transition (PRD rule, verbatim). */
  verified: boolean;
  raw: unknown;
}

export interface CreateRefundInput {
  providerReferenceId: string;
  amountCents: number;
  reason: string;
}

export interface CreateRefundResult {
  status: string;
  raw: unknown;
}

export interface PaymentProvider {
  createPayment(input: CreatePaymentInput): Promise<CreatePaymentResult>;
  getPaymentStatus(publicReference: string): Promise<PaymentStatusResult>;
  validateNotification(input: ValidateNotificationInput): Promise<ValidateNotificationResult>;
  /** Optional per the AC's own "(optional createRefund)" - no Bold
   * refund endpoint is documented anywhere in this project's approved
   * sources, so BoldPaymentProvider deliberately does not implement
   * this yet (see its own doc comment) rather than inventing one. */
  createRefund?(input: CreateRefundInput): Promise<CreateRefundResult>;
}

/** DI token - PaymentProvider is a type-only interface. */
export const PAYMENT_PROVIDER = Symbol("PAYMENT_PROVIDER");
