import { ASODEF_COMPANY } from "@asodef/config";
import { ArrowRight, Building2, Fingerprint, Handshake, Network, Scale, ShieldCheck, UserRound, UsersRound } from "lucide-react";
import { Link } from "react-router-dom";
import { EditorialSection, OutcomeList, PageCta, PublicHero, SectionIntro } from "../../components/public/PublicPage";
import { Seo } from "../../lib/seo/Seo";

const principles = [
  { title: "Claridad", text: "Explicamos el canal, la condición aplicable y el siguiente paso sin convertir posibilidades en promesas." },
  { title: "Responsabilidad", text: "Protegemos el acceso por autenticación y permisos y conservamos evidencia de acciones sensibles." },
  { title: "Servicio", text: "Conectamos cada necesidad con un flujo específico: pagos, solicitudes, documentos, beneficios o gestión empresarial." },
  { title: "Respeto por los datos", text: "Separamos autorizaciones requeridas de preferencias opcionales y vinculamos cada aceptación con su versión legal." },
];

export function AboutPage() {
  return <><Seo routeKey="about" breadcrumbs={[{ name: "Inicio", path: "/" }, { name: "Quiénes somos", path: "/quienes-somos" }]} />
    <PublicHero
      eyebrow="Identidad institucional"
      title={<>ASODEF conecta personas y organizaciones con <span className="text-brand-orange">beneficios y servicios</span></>}
      description="ASODEF S.A.S. administra relaciones con afiliados, familias, empresas y aliados mediante atención institucional y servicios digitales."
      actions={[{ label: "Consultar beneficios", to: "/beneficios", primary: true }, { label: "Ver información empresarial", to: "/legal/informacion-empresarial" }]}
      aside={<div className="rounded-[2rem] bg-brand-deep p-8 text-white shadow-e4"><Building2 aria-hidden className="h-8 w-8 text-brand-orange-light"/><p className="mt-7 text-xs font-bold uppercase tracking-[.18em] text-white/55">Identidad registrada</p><p className="mt-3 font-display text-3xl font-semibold">{ASODEF_COMPANY.legalName}</p><dl className="mt-7 grid gap-4 border-t border-white/15 pt-6 sm:grid-cols-2 lg:grid-cols-1"><div><dt className="text-xs text-white/55">NIT</dt><dd className="mt-1 font-semibold">{ASODEF_COMPANY.taxId}</dd></div><div><dt className="text-xs text-white/55">Domicilio</dt><dd className="mt-1 font-semibold">{ASODEF_COMPANY.city}, {ASODEF_COMPANY.country}</dd></div><div><dt className="text-xs text-white/55">Matrícula mercantil</dt><dd className="mt-1 font-semibold">{ASODEF_COMPANY.commercialRegistrationNumber}</dd></div></dl></div>}
    />
    <EditorialSection><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><SectionIntro eyebrow="Historia y evolución" title="Origen institucional y evolución empresarial" description="El dossier institucional sitúa el origen de ASODEF en el Fondo de Empleados de Emssanar. En 2012 evolucionó a la actual sociedad por acciones simplificada." /><div className="grid gap-4 sm:grid-cols-2"><article className="surface-panel rounded-3xl p-7"><p className="font-display text-2xl font-semibold text-brand-dark">Origen institucional</p><p className="mt-3 leading-7 text-text-muted">Nació en el entorno del Fondo de Empleados de Emssanar, según el dossier institucional.</p></article><article className="surface-panel rounded-3xl p-7"><p className="font-display text-4xl font-semibold text-brand-dark">2012</p><p className="mt-3 leading-7 text-text-muted">Evolución documentada a ASODEF S.A.S.</p></article><article className="surface-panel rounded-3xl p-7 sm:col-span-2"><Building2 aria-hidden className="h-7 w-7 text-brand-orange"/><p className="mt-4 font-semibold">Cali, Colombia</p><p className="mt-2 leading-7 text-text-muted">Domicilio registrado y punto de contacto institucional.</p></article></div></div></EditorialSection>
    <EditorialSection tone="soft"><SectionIntro eyebrow="Propósito institucional" title="Facilitar el acceso a beneficios y gestiones" description="Misión, visión y propósito son formulaciones institucionales vigentes para este sitio web." /><div className="mt-12 grid gap-5 lg:grid-cols-3"><article className="surface-panel rounded-3xl p-7"><Fingerprint aria-hidden className="h-7 w-7 text-brand-dark"/><h3 className="mt-7 font-display text-2xl font-semibold">Misión</h3><p className="mt-3 leading-7 text-text-muted">Conectar personas y organizaciones con los beneficios, la información y el trámite que corresponden.</p></article><article className="surface-panel rounded-3xl p-7"><Network aria-hidden className="h-7 w-7 text-brand-dark"/><h3 className="mt-7 font-display text-2xl font-semibold">Visión</h3><p className="mt-3 leading-7 text-text-muted">Fortalecer la relación entre afiliados, familias, empresas y aliados mediante servicios accesibles y trazables.</p></article><article className="surface-panel rounded-3xl p-7"><Scale aria-hidden className="h-7 w-7 text-brand-dark"/><h3 className="mt-7 font-display text-2xl font-semibold">Propósito</h3><p className="mt-3 leading-7 text-text-muted">Simplificar la consulta de opciones, el ejercicio de derechos y la gestión de solicitudes.</p></article></div></EditorialSection>
    <EditorialSection><SectionIntro eyebrow="Relaciones" title="Cuatro perfiles, funciones distintas" description="Cada perfil accede a los beneficios, trámites o portales habilitados para su relación con ASODEF."/><div className="mt-12 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[
      { title: "Personas y familias", to: "/soluciones/personas", icon: UserRound, text: "Consultan beneficios y usan pagos o solicitudes públicas." },
      { title: "Afiliados y usuarios", to: "/soluciones/afiliados", icon: UsersRound, text: "Acceden al portal personal y a funciones de su cuenta." },
      { title: "Empresas", to: "/empresas", icon: Building2, text: "Gestionan su relación mediante representantes autorizados." },
      { title: "Potenciales aliados", to: "/soluciones/aliados", icon: Handshake, text: "Presentan una propuesta para evaluación y seguimiento." },
    ].map(({ title, to, icon: Icon, text })=><Link key={title} to={to} className="group rounded-3xl border border-brand-dark/10 bg-white p-7 shadow-e1 transition hover:-translate-y-1 hover:shadow-e3 motion-reduce:transform-none"><Icon aria-hidden className="h-7 w-7 text-brand-orange"/><h3 className="mt-6 font-display text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-text-muted">{text}</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-brand-dark">Ver funciones<ArrowRight aria-hidden className="h-4 w-4"/></span></Link>)}</div></EditorialSection>
    <EditorialSection id="operacion"><div className="grid gap-12 lg:grid-cols-2"><div><SectionIntro eyebrow="Cómo funciona" title="Una relación conectada, no una colección de formularios" description="La experiencia pública orienta; los módulos especializados ejecutan y dejan evidencia."/><div className="mt-8"><OutcomeList items={["La autenticación y RBAC protegen cuentas, empresa y administración.", "CRM organiza intereses, empresas, oportunidades y aliados.", "Pagos consulta obligaciones, crea órdenes y conserva comprobantes con Bold como red autorizada.", "PQR y solicitudes de datos tienen radicación y seguimiento propios.", "Consentimientos, documentos legales y auditoría conservan versiones y actores."]}/></div></div><div className="rounded-[2rem] bg-brand-deep p-8 text-white shadow-e4"><ShieldCheck className="h-8 w-8 text-brand-orange-light"/><h3 className="mt-8 font-display text-3xl font-semibold">Gobierno y confianza</h3><p className="mt-4 leading-8 text-white/70">La plataforma separa áreas públicas, portales y administración; aplica permisos a las funciones internas y registra evidencia para las operaciones que la requieren.</p><dl className="mt-8 space-y-5 border-t border-white/15 pt-7"><div><dt className="text-xs uppercase tracking-wider text-white/55">Razón social</dt><dd className="mt-1 font-semibold">{ASODEF_COMPANY.legalName}</dd></div><div><dt className="text-xs uppercase tracking-wider text-white/55">NIT</dt><dd className="mt-1 font-semibold">{ASODEF_COMPANY.taxId}</dd></div><div><dt className="text-xs uppercase tracking-wider text-white/55">Registro mercantil</dt><dd className="mt-1 font-semibold">{ASODEF_COMPANY.commercialRegistrationNumber} · {ASODEF_COMPANY.chamberOfCommerce}</dd></div><div><dt className="text-xs uppercase tracking-wider text-white/55">Contacto institucional</dt><dd className="mt-1 font-semibold">{ASODEF_COMPANY.corporateEmail}</dd></div></dl></div></div></EditorialSection>
    <EditorialSection tone="soft"><SectionIntro eyebrow="Principios de operación" title="Cómo atendemos una gestión" description="Estos criterios se aplican al informar, recibir solicitudes y administrar relaciones digitales."/><div className="mt-12 grid gap-5 md:grid-cols-2">{principles.map((p,i)=><article key={p.title} className="rounded-3xl border border-brand-dark/10 bg-white p-7"><span className="text-xs font-bold text-brand-orange">0{i+1}</span><h3 className="mt-5 font-display text-2xl font-semibold">{p.title}</h3><p className="mt-3 leading-7 text-text-muted">{p.text}</p></article>)}</div></EditorialSection>
    <PageCta title="Encuentra el acceso que te corresponde" description="El orientador te conduce al beneficio, trámite o portal según tu perfil." label="Recibir orientación" />
  </>;
}
