import { ASODEF_COMPANY } from "@asodef/config";
import { Building2, Fingerprint, Network, Scale, ShieldCheck } from "lucide-react";
import { EditorialSection, OutcomeList, PageCta, PublicHero, SectionIntro } from "../../components/public/PublicPage";
import { Seo } from "../../lib/seo/Seo";

const principles = [
  { title: "Claridad", text: "Explicamos el canal, la condición aplicable y el siguiente paso sin convertir posibilidades en promesas." },
  { title: "Responsabilidad", text: "Protegemos el acceso por autenticación y permisos y conservamos evidencia de acciones sensibles." },
  { title: "Servicio", text: "Conectamos cada necesidad con un flujo específico: pagos, solicitudes, documentos, beneficios o gestión empresarial." },
  { title: "Respeto por los datos", text: "Separamos autorizaciones requeridas de preferencias opcionales y vinculamos cada aceptación con su versión legal." },
];

export function AboutPage() {
  return <><Seo routeKey="about" breadcrumbs={[{ name: "Inicio", path: "/" }, { name: "Quiénes somos", path: "/quienes-somos" }]} />
    <PublicHero eyebrow="Identidad institucional" title={<>Una organización con historia y una plataforma para <span className="text-brand-orange">gestionar relaciones</span></>} description="ASODEF S.A.S. articula beneficios, canales de atención y capacidades digitales para personas, afiliados, empresas y aliados, con información verificable y procesos trazables." actions={[{ label: "Conocer el portafolio", to: "/beneficios", primary: true }, { label: "Ver información empresarial", to: "/legal/informacion-empresarial" }]} />
    <EditorialSection><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><SectionIntro eyebrow="Historia y evolución" title="Del origen institucional a una operación digital integrada" description="El dossier institucional sitúa el origen de ASODEF en el Fondo de Empleados de Emssanar y documenta su evolución a ASODEF S.A.S. en 2012. Hoy la plataforma organiza relaciones, solicitudes y evidencia en un mismo entorno." /><div className="grid gap-4 sm:grid-cols-2"><article className="surface-panel rounded-3xl p-7"><p className="font-display text-4xl font-semibold text-brand-dark">+20 años</p><p className="mt-3 leading-7 text-text-muted">Trayectoria informada en el dossier institucional, sin convertirla en una afirmación de liderazgo de mercado.</p></article><article className="surface-panel rounded-3xl p-7"><p className="font-display text-4xl font-semibold text-brand-dark">2012</p><p className="mt-3 leading-7 text-text-muted">Año documentado de evolución a la actual sociedad por acciones simplificada.</p></article><article className="surface-panel rounded-3xl p-7 sm:col-span-2"><Building2 className="h-7 w-7 text-brand-orange"/><p className="mt-4 font-semibold">Operación desde Cali, Colombia</p><p className="mt-2 leading-7 text-text-muted">La sede y la información registral se presentan con su fuente corporativa; no se infieren sedes adicionales.</p></article></div></div></EditorialSection>
    <EditorialSection tone="soft"><SectionIntro eyebrow="Propósito institucional" title="Facilitar acceso, orientación y gestión responsable" description="Estas formulaciones son el marco editorial institucional vigente para la web; no se presentan como citas históricas." /><div className="mt-12 grid gap-5 lg:grid-cols-3"><article className="surface-panel rounded-3xl p-7"><Fingerprint className="h-7 w-7 text-brand-dark"/><h3 className="mt-7 font-display text-2xl font-semibold">Misión</h3><p className="mt-3 leading-7 text-text-muted">Conectar a personas y organizaciones con beneficios, información y canales de gestión pertinentes, mediante una atención clara y una operación digital responsable.</p></article><article className="surface-panel rounded-3xl p-7"><Network className="h-7 w-7 text-brand-dark"/><h3 className="mt-7 font-display text-2xl font-semibold">Visión</h3><p className="mt-3 leading-7 text-text-muted">Consolidar una experiencia institucional accesible y trazable que fortalezca la relación entre afiliados, familias, empresas y aliados.</p></article><article className="surface-panel rounded-3xl p-7"><Scale className="h-7 w-7 text-brand-dark"/><h3 className="mt-7 font-display text-2xl font-semibold">Propósito</h3><p className="mt-3 leading-7 text-text-muted">Reducir la fricción para comprender una opción, ejercer un derecho, completar una gestión o encontrar el canal adecuado.</p></article></div></EditorialSection>
    <EditorialSection id="operacion"><div className="grid gap-12 lg:grid-cols-2"><div><SectionIntro eyebrow="Cómo funciona" title="Una relación conectada, no una colección de formularios" description="La experiencia pública orienta; los módulos especializados ejecutan y dejan evidencia."/><div className="mt-8"><OutcomeList items={["La autenticación y RBAC protegen cuentas, empresa y administración.", "CRM organiza intereses, empresas, oportunidades y aliados.", "Pagos consulta obligaciones, crea órdenes y conserva comprobantes con Bold como red autorizada.", "PQR y solicitudes de datos tienen radicación y seguimiento propios.", "Consentimientos, documentos legales y auditoría conservan versiones y actores."]}/></div></div><div className="rounded-[2rem] bg-brand-deep p-8 text-white shadow-e4"><ShieldCheck className="h-8 w-8 text-brand-orange-light"/><h3 className="mt-8 font-display text-3xl font-semibold">Gobierno y confianza</h3><p className="mt-4 leading-8 text-white/70">La plataforma separa áreas públicas, portales y administración; aplica permisos a las funciones internas y registra evidencia para las operaciones que la requieren.</p><dl className="mt-8 space-y-5 border-t border-white/15 pt-7"><div><dt className="text-xs uppercase tracking-wider text-white/55">Razón social</dt><dd className="mt-1 font-semibold">{ASODEF_COMPANY.legalName}</dd></div><div><dt className="text-xs uppercase tracking-wider text-white/55">NIT</dt><dd className="mt-1 font-semibold">{ASODEF_COMPANY.taxId}</dd></div><div><dt className="text-xs uppercase tracking-wider text-white/55">Registro mercantil</dt><dd className="mt-1 font-semibold">{ASODEF_COMPANY.commercialRegistrationNumber} · {ASODEF_COMPANY.chamberOfCommerce}</dd></div><div><dt className="text-xs uppercase tracking-wider text-white/55">Contacto institucional</dt><dd className="mt-1 font-semibold">{ASODEF_COMPANY.corporateEmail}</dd></div></dl></div></div></EditorialSection>
    <EditorialSection tone="soft"><SectionIntro eyebrow="Principios de operación" title="Criterios que orientan la experiencia" description="Aplican a la forma en que ASODEF informa, recibe solicitudes y gestiona relaciones digitales."/><div className="mt-12 grid gap-5 md:grid-cols-2">{principles.map((p,i)=><article key={p.title} className="rounded-3xl border border-brand-dark/10 bg-white p-7"><span className="text-xs font-bold text-brand-orange">0{i+1}</span><h3 className="mt-5 font-display text-2xl font-semibold">{p.title}</h3><p className="mt-3 leading-7 text-text-muted">{p.text}</p></article>)}</div></EditorialSection>
    <PageCta title="Encuentra el canal que corresponde a tu relación con ASODEF" description="El recorrido guiado evita pedir información innecesaria y te conduce al portal, trámite o registro adecuado." />
  </>;
}
