import { useMemo } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { ArrowRight, SlidersHorizontal } from "lucide-react";
import { EditorialSection, PageCta, PublicHero, SectionIntro } from "../../components/public/PublicPage";
import { BENEFITS, type BenefitAudience, type BenefitNeed } from "../../lib/public-content/benefits";
import { Seo } from "../../lib/seo/Seo";

const audiences: { value: "todas" | BenefitAudience; label: string }[] = [{ value: "todas", label: "Todas las audiencias" }, { value: "personas", label: "Personas" }, { value: "afiliados", label: "Afiliados" }, { value: "empresas", label: "Empresas" }, { value: "aliados", label: "Aliados" }];
const needs: { value: "todas" | BenefitNeed; label: string }[] = [{ value: "todas", label: "Todas las necesidades" }, { value: "proteccion", label: "Protección" }, { value: "salud", label: "Salud" }, { value: "orientacion", label: "Orientación" }, { value: "movilidad", label: "Movilidad" }, { value: "educacion", label: "Educación" }, { value: "ahorro", label: "Ahorro" }];

export function BenefitsPage() {
  const [params, setParams] = useSearchParams();
  const audience = (params.get("audiencia") ?? "todas") as "todas" | BenefitAudience;
  const need = (params.get("necesidad") ?? "todas") as "todas" | BenefitNeed;
  const filtered = useMemo(() => BENEFITS.filter(item => (audience === "todas" || (item.audience as readonly BenefitAudience[]).includes(audience)) && (need === "todas" || (item.needs as readonly BenefitNeed[]).includes(need))), [audience, need]);
  function update(key: string, value: string) { const next = new URLSearchParams(params); value === "todas" ? next.delete(key) : next.set(key, value); setParams(next, { replace: true }); }
  return <><Seo routeKey="benefits" breadcrumbs={[{ name: "Inicio", path: "/" }, { name: "Beneficios", path: "/beneficios" }]} />
    <PublicHero eyebrow="Portafolio verificado" title={<>Valor disponible, explicado con <span className="text-brand-orange">condiciones claras</span></>} description="Explora las categorías documentadas por ASODEF. Cada página explica el propósito, el proceso y los límites sin inventar coberturas, precios o disponibilidad." actions={[{ label: "Encontrar por mi perfil", to: "/comenzar", primary: true }, { label: "Ver soluciones", to: "/soluciones" }]} />
    <EditorialSection><SectionIntro eyebrow="Explorar" title="Filtra por audiencia y necesidad" description="La selección permanece en la URL para que puedas compartir o retomar la misma vista."/><div className="mt-9 grid gap-4 rounded-3xl border border-brand-dark/10 bg-white p-5 shadow-e1 sm:grid-cols-2"><label className="text-sm font-semibold"><span className="mb-2 flex items-center gap-2"><SlidersHorizontal className="h-4 w-4"/>Audiencia</span><select className="min-h-12 w-full rounded-xl border border-brand-dark/15 bg-white px-4" value={audience} onChange={e=>update("audiencia", e.target.value)}>{audiences.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label><label className="text-sm font-semibold"><span className="mb-2 block">Necesidad</span><select className="min-h-12 w-full rounded-xl border border-brand-dark/15 bg-white px-4" value={need} onChange={e=>update("necesidad", e.target.value)}>{needs.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label></div>
    <p className="mt-8 text-sm font-medium text-text-muted" aria-live="polite">{filtered.length} {filtered.length === 1 ? "categoría encontrada" : "categorías encontradas"}</p>
    {filtered.length ? <div className="mt-5 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{filtered.map((item,index)=><article key={item.slug} className="group flex min-h-80 flex-col rounded-[1.75rem] border border-brand-dark/10 bg-white p-7 shadow-e1 transition hover:-translate-y-1 hover:shadow-e3"><span className="text-xs font-bold tracking-[.18em] text-brand-orange">{String(index+1).padStart(2,"0")}</span><h2 className="mt-7 font-display text-2xl font-semibold tracking-tight">{item.title}</h2><p className="mt-4 flex-1 leading-7 text-text-muted">{item.summary}</p><p className="mt-5 text-xs font-semibold uppercase tracking-wider text-brand-dark">{item.needs.join(" · ")}</p><Link className="mt-6 inline-flex items-center gap-2 font-semibold text-brand-dark" to={`/beneficios/${item.slug}`}>Comprender este beneficio<ArrowRight className="h-4 w-4 transition group-hover:translate-x-1"/></Link></article>)}</div> : <div className="mt-5 rounded-3xl border border-dashed border-brand-dark/20 p-10 text-center"><h2 className="font-display text-2xl font-semibold">No hay una categoría con ambos filtros</h2><p className="mt-3 text-text-muted">Cambia una selección o usa el orientador para encontrar el canal adecuado.</p><button className="public-button-secondary mt-6" onClick={()=>setParams({}, { replace: true })}>Limpiar filtros</button></div>}</EditorialSection>
    <PageCta title="¿No sabes qué categoría corresponde?" description="El orientador hace preguntas mínimas y te conduce al beneficio, portal o trámite apropiado." />
  </>;
}
