import { forwardRef, useEffect, useMemo, useRef, useState } from "react";
import type React from "react";
import { useMutation } from "@tanstack/react-query";
import { ArrowLeft, ArrowRight, CheckCircle2, CreditCard, Database, MessageSquareText } from "lucide-react";
import { Link, useLocation, useSearchParams } from "react-router-dom";
import { submitGuidedLead, type GuidedAudience, type GuidedLeadRequest } from "../../lib/leads/guided-leads";
import { Seo } from "../../lib/seo/Seo";

type DirectProfile = "payment" | "pqr" | "data";
type Profile = GuidedAudience | DirectProfile;
interface FunnelState { profile?: Profile; need?: string; fullName?: string; email?: string; phone?: string; company?: string; taxId?: string; role?: string; city?: string; message?: string; preferredContact?: "email"|"whatsapp"|"phone"; dataProcessingConsent?: boolean; commercialConsent?: boolean; emailConsent?: boolean; whatsappConsent?: boolean; }
const STORAGE_KEY = "asodef:guided-funnel:v1";
const direct = { payment: { title: "Soporte o gestión de pago", text: "Consulta la obligación en el Centro de pagos; no necesitas crear un lead.", to: "/pagos", label: "Ir al Centro de pagos", icon: CreditCard }, pqr: { title: "PQR o solicitud de atención", text: "Radica el caso en el flujo formal y conserva su referencia.", to: "/pqr", label: "Radicar una PQR", icon: MessageSquareText }, data: { title: "Solicitud sobre datos personales", text: "Ejerce tus derechos en el proceso especializado de titulares.", to: "/solicitudes-de-datos", label: "Iniciar solicitud de datos", icon: Database } } as const;
const profiles: { value: Profile; title: string; text: string }[] = [
  { value: "person", title: "Persona", text: "Quiero orientación sobre una necesidad o beneficio." }, { value: "affiliate", title: "Afiliado o usuario", text: "Tengo una relación o cuenta con ASODEF." }, { value: "company", title: "Represento una empresa", text: "Tengo una necesidad organizacional." }, { value: "ally", title: "Potencial aliado", text: "Quiero presentar una propuesta para evaluación." }, { value: "payment", title: "Pago", text: "Necesito consultar una obligación o comprobante." }, { value: "pqr", title: "PQR", text: "Quiero radicar una petición, queja o reclamo." }, { value: "data", title: "Datos personales", text: "Quiero ejercer un derecho sobre mis datos." }, { value: "orientation", title: "Orientación general", text: "Aún no identifico el canal correcto." },
];

function loadState(): FunnelState { try { return JSON.parse(sessionStorage.getItem(STORAGE_KEY) ?? "{}") as FunnelState; } catch { return {}; } }
function createKey() { return typeof crypto.randomUUID === "function" ? crypto.randomUUID() : `${Date.now()}-${Math.random().toString(36).slice(2)}`; }

export function GuidedStartPage() {
  const [search] = useSearchParams(); const location = useLocation();
  const initialProfile = ({ personas:"person", afiliados:"affiliate", empresa:"company", aliado:"ally" } as Record<string,Profile>)[search.get("perfil")??""];
  const [state,setState]=useState<FunnelState>(()=>({ ...loadState(), ...(initialProfile?{profile:initialProfile}:{}), ...(search.get("beneficio")?{need:`Beneficio: ${search.get("beneficio")}`}:{}) }));
  const [step,setStep]=useState(initialProfile?1:0); const [error,setError]=useState(""); const [idempotencyKey]=useState(createKey); const headingRef=useRef<HTMLHeadingElement>(null);
  const mutation=useMutation({mutationFn:submitGuidedLead});
  const isOrg=state.profile==="company"||state.profile==="ally"; const directRoute=state.profile && state.profile in direct ? direct[state.profile as DirectProfile] : null;
  const total=directRoute?2:6; const progress=Math.min(100,((step+1)/total)*100);
  useEffect(()=>{sessionStorage.setItem(STORAGE_KEY,JSON.stringify(state));},[state]);
  useEffect(()=>{headingRef.current?.focus();},[step]);
  const campaign=useMemo(()=>Object.fromEntries(["utm_source","utm_medium","utm_campaign","utm_term","utm_content"].flatMap(key=>{const value=search.get(key);return value?[[key.replace(/_([a-z])/g,(_,c:string)=>c.toUpperCase()),value]]:[]})),[search]);
  function update<K extends keyof FunnelState>(key:K,value:FunnelState[K]){setState(current=>({...current,[key]:value}));setError("");}
  function next(){ if(step===0&&!state.profile)return setError("Selecciona el perfil que mejor describe tu visita."); if(step===1&&!directRoute&&!state.need?.trim())return setError("Describe brevemente lo que necesitas."); if(step===2&&(!state.fullName?.trim()||!state.email?.includes("@")||(isOrg&&!state.company?.trim())))return setError("Completa el nombre, un correo válido y los datos de organización que aplican."); if(step===3&&(!state.preferredContact||(state.preferredContact!=="email"&&!state.phone?.trim())))return setError("Elige un canal y completa el dato necesario."); if(step===4&&!state.dataProcessingConsent)return setError("La autorización de tratamiento de datos es necesaria para enviar la solicitud."); setStep(value=>value+1); }
  async function submit(){setError(""); if(!state.profile||state.profile in direct)return; const request:GuidedLeadRequest={audience:state.profile as GuidedAudience,need:state.need??"Orientación general",fullName:state.fullName??"",email:state.email??"",phone:state.phone,company:state.company,taxId:state.taxId,role:state.role,city:state.city,message:state.message??state.need??"Solicitud de orientación",preferredContact:state.preferredContact??"email",dataProcessingConsent:true,commercialConsent:state.commercialConsent,emailConsent:state.emailConsent,whatsappConsent:state.whatsappConsent,idempotencyKey,entryRoute:`${location.pathname}${location.search}`,campaign}; try{await mutation.mutateAsync(request);sessionStorage.removeItem(STORAGE_KEY);}catch(e){setError(e instanceof Error?e.message:"No pudimos registrar la solicitud. Revisa los datos e intenta de nuevo.");}}
  if(mutation.isSuccess)return <><Seo routeKey="start"/><main className="mx-auto flex min-h-[70svh] max-w-3xl items-center px-5 py-16"><div className="w-full rounded-[2rem] border border-brand-dark/10 bg-white p-8 text-center shadow-e3 sm:p-12"><CheckCircle2 className="mx-auto h-12 w-12 text-success"/><h1 className="mt-7 font-display text-4xl font-semibold">Solicitud registrada</h1><p className="mt-4 leading-7 text-text-muted">Conserva esta referencia para identificar la gestión.</p><p className="mx-auto mt-6 w-fit rounded-xl bg-bg-soft px-5 py-3 font-mono font-bold text-brand-dark">{mutation.data.reference}</p><Link className="public-button-primary mt-8" to="/">Volver al inicio</Link></div></main></>;
  return <><Seo routeKey="start" breadcrumbs={[{name:"Inicio",path:"/"},{name:"Comenzar",path:"/comenzar"}]}/><section className="min-h-[78svh] bg-[radial-gradient(circle_at_80%_10%,rgba(128,174,58,.15),transparent_26rem)] py-12 sm:py-16"><div className="mx-auto max-w-4xl px-5 sm:px-8"><div className="flex items-center justify-between gap-4 text-sm"><p className="font-semibold text-brand-dark">Orientador ASODEF</p><p aria-live="polite" className="text-text-muted">Paso {Math.min(step+1,total)} de {total}</p></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-brand-dark/10"><div className="h-full rounded-full bg-brand-orange transition-[width] motion-reduce:transition-none" style={{width:`${progress}%`}}/></div><div className="mt-8 rounded-[2rem] border border-brand-dark/10 bg-white p-6 shadow-e3 sm:p-10"><div aria-live="polite" className="sr-only">Paso {step+1}</div>
  {step===0&&<div><p className="text-sm font-semibold text-brand-orange">Primero, el contexto</p><h1 ref={headingRef} tabIndex={-1} className="mt-3 font-display text-3xl font-semibold focus:outline-none sm:text-5xl">¿Qué describe mejor tu visita?</h1><div role="radiogroup" aria-label="Perfil de visita" className="mt-8 grid gap-3 sm:grid-cols-2">{profiles.map(p=><button type="button" role="radio" aria-checked={state.profile===p.value} key={p.value} onClick={()=>update("profile",p.value)} className={`rounded-2xl border p-5 text-left transition ${state.profile===p.value?"border-brand-dark bg-brand-dark text-white shadow-e2":"border-brand-dark/10 hover:border-brand-dark/30 hover:bg-bg-soft"}`}><span className="font-semibold">{p.title}</span><span className={`mt-1 block text-sm leading-6 ${state.profile===p.value?"text-white/70":"text-text-muted"}`}>{p.text}</span></button>)}</div></div>}
  {step===1&&directRoute&&<div>{(()=>{const Icon=directRoute.icon;return <><Icon className="h-9 w-9 text-brand-orange"/><h1 ref={headingRef} tabIndex={-1} className="mt-6 font-display text-4xl font-semibold focus:outline-none">{directRoute.title}</h1><p className="mt-4 text-lg leading-8 text-text-muted">{directRoute.text}</p><Link className="public-button-primary mt-8" to={directRoute.to}>{directRoute.label}<ArrowRight className="h-4 w-4"/></Link></>})()}</div>}
  {step===1&&!directRoute&&<Question ref={headingRef} title="¿Qué necesitas resolver?" hint="Una frase concreta es suficiente."><textarea autoFocus value={state.need??""} onChange={e=>update("need",e.target.value)} className="min-h-32 w-full rounded-2xl border border-brand-dark/15 p-4" maxLength={120} placeholder="Ejemplo: conocer una categoría de beneficio para mi familia"/></Question>}
  {step===2&&<Question ref={headingRef} title={isOrg?"¿Quién representa a la organización?":"¿Cómo podemos identificarte?"} hint="Usaremos estos datos únicamente para gestionar esta solicitud."><div className="grid gap-4 sm:grid-cols-2"><Field label="Nombre completo" value={state.fullName} onChange={v=>update("fullName",v)}/><Field type="email" label="Correo electrónico" value={state.email} onChange={v=>update("email",v)}/>{isOrg&&<><Field label="Empresa" value={state.company} onChange={v=>update("company",v)}/><Field label="Rol de contacto" value={state.role} onChange={v=>update("role",v)}/><Field label="NIT (si es necesario para la gestión)" value={state.taxId} onChange={v=>update("taxId",v)}/></>}<Field label="Ciudad (opcional)" value={state.city} onChange={v=>update("city",v)}/></div></Question>}
  {step===3&&<Question ref={headingRef} title="¿Por cuál canal prefieres continuar?" hint="Correo y WhatsApp requieren una elección explícita."><div className="grid gap-3 sm:grid-cols-3">{(["email","whatsapp","phone"] as const).map(channel=><button role="radio" aria-checked={state.preferredContact===channel} type="button" key={channel} onClick={()=>update("preferredContact",channel)} className={`rounded-xl border p-4 font-semibold ${state.preferredContact===channel?"border-brand-dark bg-brand-dark text-white":"border-brand-dark/15"}`}>{channel==="email"?"Correo":channel==="whatsapp"?"WhatsApp":"Llamada"}</button>)}</div>{state.preferredContact!=="email"&&<div className="mt-5"><Field label="Teléfono" value={state.phone} onChange={v=>update("phone",v)}/></div>}<div className="mt-6 space-y-3">{state.preferredContact==="email"&&<Check label="Acepto recibir la respuesta por correo electrónico." checked={!!state.emailConsent} onChange={v=>update("emailConsent",v)}/>} {state.preferredContact==="whatsapp"&&<Check label="Acepto recibir la respuesta por WhatsApp." checked={!!state.whatsappConsent} onChange={v=>update("whatsappConsent",v)}/>}</div></Question>}
  {step===4&&<Question ref={headingRef} title="Tus decisiones de privacidad" hint="La atención no depende de aceptar comunicaciones comerciales."><div className="space-y-5"><Check checked={!!state.dataProcessingConsent} onChange={v=>update("dataProcessingConsent",v)} label={<>Autorizo el tratamiento necesario para gestionar esta solicitud. <Link className="underline" target="_blank" to="/legal/tratamiento-de-datos">Consultar política</Link>.</>}/><Check checked={!!state.commercialConsent} onChange={v=>update("commercialConsent",v)} label={<>Opcional: acepto comunicaciones comerciales. <Link className="underline" target="_blank" to="/legal/consentimiento-comunicaciones-comerciales">Consultar consentimiento</Link>.</>}/></div></Question>}
  {step===5&&<Question ref={headingRef} title="Revisa antes de enviar" hint="Puedes regresar para corregir cualquier dato."><dl className="grid gap-4 rounded-2xl bg-bg-soft p-5 sm:grid-cols-2"><Review label="Perfil" value={state.profile}/><Review label="Necesidad" value={state.need}/><Review label="Nombre" value={state.fullName}/><Review label="Correo" value={state.email}/><Review label="Organización" value={state.company}/><Review label="Canal" value={state.preferredContact}/></dl></Question>}
  {error&&<p role="alert" className="mt-6 rounded-xl bg-danger/10 p-4 text-sm font-medium text-danger">{error}</p>} {(!directRoute||step===0)&&<div className="mt-8 flex items-center justify-between gap-3"><button type="button" disabled={step===0} onClick={()=>setStep(v=>Math.max(0,v-1))} className="public-button-secondary disabled:invisible"><ArrowLeft className="h-4 w-4"/>Atrás</button>{step<5?<button type="button" onClick={next} className="public-button-primary">Continuar<ArrowRight className="h-4 w-4"/></button>:<button type="button" disabled={mutation.isPending} onClick={submit} className="public-button-primary disabled:opacity-60">{mutation.isPending?"Registrando…":"Confirmar y enviar"}</button>}</div>}{directRoute&&step===1&&<button type="button" onClick={()=>{setStep(0);update("profile",undefined)}} className="public-button-secondary mt-8"><ArrowLeft className="h-4 w-4"/>Elegir otra ruta</button>}</div><p className="mt-6 text-center text-xs leading-5 text-text-muted">Tu avance se conserva en este navegador durante la sesión. Puedes limpiarlo regresando al primer paso y cambiando de ruta.</p></div></section></>;
}

const Question=forwardRef<HTMLHeadingElement, { title:string; hint:string; children:React.ReactNode }>(({title,hint,children},ref)=><div><h1 ref={ref} tabIndex={-1} className="font-display text-3xl font-semibold tracking-tight focus:outline-none sm:text-5xl">{title}</h1><p className="mt-4 leading-7 text-text-muted">{hint}</p><div className="mt-8">{children}</div></div>);
const Field=({label,value,onChange,type="text"}:{label:string;value?:string;onChange:(v:string)=>void;type?:string})=><label className="text-sm font-semibold">{label}<input type={type} value={value??""} onChange={e=>onChange(e.target.value)} className="mt-2 min-h-12 w-full rounded-xl border border-brand-dark/15 px-4 font-normal"/></label>;
const Check=({label,checked,onChange}:{label:React.ReactNode;checked:boolean;onChange:(v:boolean)=>void})=><label className="flex gap-3 rounded-xl border border-brand-dark/10 p-4 text-sm leading-6"><input className="mt-1 h-4 w-4" type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/><span>{label}</span></label>;
const Review=({label,value}:{label:string;value?:string})=>value?<div><dt className="text-xs font-bold uppercase tracking-wider text-text-muted">{label}</dt><dd className="mt-1 font-medium">{value}</dd></div>:null;
