import { Link } from "react-router-dom";
import { ArrowRight, Building2, CreditCard, FileCheck2, HeartHandshake, ShieldCheck, UsersRound } from "lucide-react";

const nodes = [
  { label: "Personas", icon: UsersRound, position: "left-[7%] top-[11%]" },
  { label: "Empresas", icon: Building2, position: "right-[4%] top-[18%]" },
  { label: "Beneficios", icon: HeartHandshake, position: "left-[3%] bottom-[18%]" },
  { label: "Pagos", icon: CreditCard, position: "right-[7%] bottom-[12%]" },
] as const;

export function FlagshipHero() {
  return <section className="relative isolate overflow-hidden border-b border-brand-dark/10 py-16 sm:py-20 lg:min-h-[760px] lg:py-24"><div aria-hidden className="absolute inset-0 -z-20 bg-[linear-gradient(120deg,#f8faf6_0%,#eef4ed_46%,#f4f5f1_100%)]"/><div aria-hidden className="absolute -right-52 -top-60 -z-10 h-[45rem] w-[45rem] rounded-full border border-brand-dark/10 bg-brand-light/10 blur-[1px]"/>
  <div className="mx-auto grid max-w-7xl items-center gap-14 px-5 sm:px-8 lg:grid-cols-[1.05fr_.95fr] lg:px-12"><div className="relative z-10"><p className="inline-flex items-center gap-2 rounded-full border border-brand-dark/15 bg-white/75 px-4 py-2 text-xs font-bold uppercase tracking-[.16em] text-brand-dark shadow-e1"><ShieldCheck className="h-4 w-4"/>ASODEF · gestión institucional conectada</p><h1 className="mt-7 max-w-4xl font-display text-[clamp(3.1rem,6.4vw,6.2rem)] font-semibold leading-[.91] tracking-[-.065em] text-text-main">Una ruta clara entre tu necesidad y la <span className="text-brand-orange">gestión correcta.</span></h1><p className="mt-8 max-w-2xl text-lg leading-8 text-text-muted sm:text-xl">ASODEF conecta personas, afiliados, empresas y aliados con beneficios, pagos, solicitudes, documentos y portales en una experiencia verificable.</p><div className="mt-9 flex flex-wrap gap-3"><Link to="/comenzar" className="public-button-primary">Encontrar mi ruta<ArrowRight className="h-4 w-4"/></Link><Link to="/beneficios" className="public-button-secondary">Explorar beneficios</Link></div><div className="mt-10 flex flex-wrap gap-x-7 gap-y-3 border-t border-brand-dark/10 pt-6 text-sm font-medium text-text-muted"><span>Autenticación y permisos</span><span>Consentimientos versionados</span><span>Canales especializados</span></div></div>
  <div className="relative mx-auto aspect-square w-full max-w-[36rem]" aria-label="Ecosistema digital ASODEF"><div className="absolute inset-[16%] rounded-full border border-brand-dark/15 bg-white/70 shadow-e4 backdrop-blur-xl"><div className="absolute inset-[18%] flex flex-col items-center justify-center rounded-full bg-brand-deep text-center text-white shadow-e3"><span className="text-xs font-bold uppercase tracking-[.2em] text-brand-orange-light">ASODEF</span><span className="mt-2 font-display text-2xl font-semibold">Ecosistema digital</span><span className="mt-2 max-w-40 text-xs leading-5 text-white/65">Información, gestión y evidencia conectadas</span></div><div aria-hidden className="absolute inset-[8%] animate-[spin_36s_linear_infinite] rounded-full border border-dashed border-brand-dark/20 motion-reduce:animate-none"/></div>{nodes.map(({label,icon:Icon,position})=><div key={label} className={`absolute ${position} flex min-w-32 items-center gap-3 rounded-2xl border border-white bg-white/90 p-4 shadow-e3 backdrop-blur`}><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-brand-dark/10"><Icon className="h-5 w-5 text-brand-dark"/></span><span className="text-sm font-semibold">{label}</span></div>)}<div className="absolute bottom-[2%] left-1/2 flex -translate-x-1/2 items-center gap-2 rounded-full bg-brand-orange px-4 py-2 text-xs font-bold text-white shadow-e2"><FileCheck2 className="h-4 w-4"/>Solicitudes y evidencia</div></div></div></section>;
}
