import { Link } from "react-router-dom";
import { ArrowRight, Building2, CreditCard, FileText, Handshake, HeartHandshake, ShieldCheck, UserRound, UsersRound } from "lucide-react";
import { EditorialSection, NumberedProcess, PageCta, SectionIntro } from "../../components/public/PublicPage";
import { VERIFIED_PUBLIC_INDICATORS, VerifiedIndicators } from "../../components/public/metrics";
import { BENEFITS } from "../../lib/public-content/benefits";
import { AUDIENCES } from "../../lib/public-content/audiences";
import { Seo } from "../../lib/seo/Seo";
import { FlagshipHero } from "./FlagshipHero";

const audienceIcons = { personas: UserRound, afiliados: UsersRound, empresas: Building2, aliados: Handshake };

export function HomePage() {
  return <><Seo routeKey="home"/><FlagshipHero/>
  <section className="border-b border-brand-dark/10 bg-white/70 py-14 sm:py-20 lg:py-24" aria-labelledby="trajectory-heading"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-12"><div className="grid gap-10 lg:grid-cols-[minmax(0,.82fr)_minmax(0,1.18fr)] lg:items-center lg:gap-16 xl:gap-20"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-brand-dark">Trayectoria institucional</p><h2 id="trajectory-heading" className="mt-3 max-w-xl font-display text-3xl font-semibold leading-tight tracking-[-.035em] sm:text-4xl lg:text-[2.7rem] xl:text-5xl">Más de una década construyendo relaciones de confianza.</h2><p className="mt-4 max-w-xl text-sm leading-6 text-text-muted sm:text-base sm:leading-7">Desde 2012, ASODEF S.A.S. organiza el acceso a sus servicios con una visión centrada en el acompañamiento y la atención.</p></div><VerifiedIndicators indicators={VERIFIED_PUBLIC_INDICATORS}/></div></div></section>
  <EditorialSection><div className="grid gap-14 lg:grid-cols-[.8fr_1.2fr]"><SectionIntro eyebrow="Qué puedes hacer" title="Consulta, gestiona y conserva una referencia" description="La zona pública orienta cada necesidad. Pagos, PQR, solicitudes de datos y portales completan la gestión en su módulo específico."/><div className="grid gap-4 sm:grid-cols-2"><article className="rounded-3xl bg-brand-deep p-7 text-white shadow-e3"><CreditCard className="h-7 w-7 text-brand-orange-light"/><h3 className="mt-7 font-display text-2xl font-semibold">Gestiones públicas</h3><p className="mt-3 leading-7 text-white/70">Consulta pagos, radica casos y realiza seguimiento con la referencia generada.</p></article><article className="surface-panel rounded-3xl p-7"><ShieldCheck className="h-7 w-7 text-brand-orange"/><h3 className="mt-7 font-display text-2xl font-semibold">Portales protegidos</h3><p className="mt-3 leading-7 text-text-muted">Afiliados y empresas verifican su identidad antes de consultar información privada.</p></article></div></div></EditorialSection>
  <EditorialSection tone="soft"><SectionIntro eyebrow="Elige tu perfil" title="Accede a las funciones que te corresponden" description="Cada perfil reúne sus beneficios, trámites y portales disponibles."/><div className="mt-12 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{AUDIENCES.map(a=>{const Icon=audienceIcons[a.slug]; return <Link key={a.slug} to={`/soluciones/${a.slug}`} className="group flex flex-col rounded-3xl bg-white p-7 shadow-e1 transition hover:-translate-y-1 hover:shadow-e3 motion-reduce:transform-none"><Icon className="h-7 w-7 text-brand-orange"/><h3 className="mt-7 font-display text-2xl font-semibold">{a.title}</h3><p className="mt-3 flex-1 leading-7 text-text-muted">{a.summary}</p><span className="mt-6 inline-flex items-center gap-2 font-semibold text-brand-dark">Ver opciones<ArrowRight className="h-4 w-4 transition group-hover:translate-x-1 motion-reduce:transform-none"/></span></Link>})}</div></EditorialSection>
  <EditorialSection><div className="flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><SectionIntro eyebrow="Beneficios" title="Consulta el portafolio por necesidad" description="Cada categoría indica a quién aplica, qué información puede requerir y cómo continuar."/><Link to="/beneficios" className="public-button-secondary shrink-0">Ver las {BENEFITS.length} categorías<ArrowRight className="h-4 w-4"/></Link></div><div className="mt-12 grid gap-x-8 border-y border-brand-dark/10 md:grid-cols-2">{BENEFITS.slice(0,6).map((b,i)=><Link to={`/beneficios/${b.slug}`} key={b.slug} className="group flex items-center justify-between gap-5 border-b border-brand-dark/10 py-6 last:border-0 md:[&:nth-last-child(-n+2)]:border-b-0"><div><span className="text-xs font-bold text-brand-orange">0{i+1}</span><h3 className="mt-2 font-display text-xl font-semibold">{b.title}</h3><p className="mt-2 text-sm leading-6 text-text-muted">{b.summary}</p></div><ArrowRight className="h-5 w-5 shrink-0 text-brand-dark transition group-hover:translate-x-1 motion-reduce:transform-none"/></Link>)}</div></EditorialSection>
  <EditorialSection tone="dark"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-brand-orange-light">Cómo funciona</p><h2 className="mt-4 font-display text-4xl font-semibold tracking-tight sm:text-5xl">Tres pasos para continuar</h2><p className="mt-5 text-lg leading-8 text-white/70">Empieza con tu perfil y termina en el servicio que procesa la gestión.</p></div><NumberedProcess items={["Elige tu perfil y la tarea que necesitas realizar.", "Revisa el beneficio, portal o trámite aplicable.", "Completa la gestión y guarda la referencia cuando se genere."]}/></div></EditorialSection>
  <EditorialSection><div className="grid gap-5 lg:grid-cols-3"><article className="rounded-[2rem] border border-brand-dark/10 bg-white p-8 shadow-e2 lg:col-span-2"><HeartHandshake className="h-8 w-8 text-brand-orange"/><h2 className="mt-8 font-display text-3xl font-semibold">Empresas y potenciales aliados</h2><p className="mt-4 max-w-2xl leading-7 text-text-muted">Presentan una necesidad organizacional o una propuesta; el envío crea seguimiento real en CRM, sin conceder acceso ni confirmar una relación contractual.</p><Link className="public-button-primary mt-7" to="/soluciones/empresas">Conocer la ruta empresarial<ArrowRight className="h-4 w-4"/></Link></article><div className="grid gap-5"><Link to="/pagos" className="rounded-3xl bg-bg-soft p-6"><CreditCard className="h-6 w-6 text-brand-dark"/><h3 className="mt-5 font-display text-xl font-semibold">Consultar un pago</h3><p className="mt-2 text-sm leading-6 text-text-muted">Obligaciones, orden, Bold y comprobante.</p></Link><Link to="/recursos" className="rounded-3xl bg-bg-soft p-6"><FileText className="h-6 w-6 text-brand-dark"/><h3 className="mt-5 font-display text-xl font-semibold">Gestionar una solicitud</h3><p className="mt-2 text-sm leading-6 text-text-muted">PQR, datos personales y orientación.</p></Link></div></div></EditorialSection>
  <EditorialSection tone="soft"><div className="grid items-center gap-12 lg:grid-cols-2"><SectionIntro eyebrow="Protección de datos" title="Cada consentimiento conserva su contexto" description="La autorización requerida se separa de correo, WhatsApp y comunicaciones comerciales opcionales."/><div className="grid gap-3"><Link className="rounded-2xl border border-brand-dark/10 bg-white p-5 font-semibold text-brand-dark" to="/legal/tratamiento-de-datos">Política de tratamiento de datos</Link><Link className="rounded-2xl border border-brand-dark/10 bg-white p-5 font-semibold text-brand-dark" to="/legal/politica-de-privacidad">Política de privacidad</Link><Link className="rounded-2xl border border-brand-dark/10 bg-white p-5 font-semibold text-brand-dark" to="/legal">Consultar los 21 documentos vigentes</Link></div></div></EditorialSection>
  <PageCta title="¿Qué necesitas hacer?" description="Responde unas preguntas breves para abrir el beneficio, pago, solicitud o portal correspondiente." label="Recibir orientación" />
  </>;
}
