import { Link } from "react-router-dom";
import { ArrowRight, Building2, CreditCard, FileText, Handshake, HeartHandshake, Network, ShieldCheck, UserRound, UsersRound } from "lucide-react";
import { EditorialSection, NumberedProcess, PageCta, SectionIntro } from "../../components/public/PublicPage";
import { BENEFITS } from "../../lib/public-content/benefits";
import { AUDIENCES } from "../../lib/public-content/audiences";
import { Seo } from "../../lib/seo/Seo";
import { FlagshipHero } from "./FlagshipHero";

const audienceIcons = { personas: UserRound, afiliados: UsersRound, empresas: Building2, aliados: Handshake };

export function HomePage() {
  return <><Seo routeKey="home"/><FlagshipHero/>
  <section className="border-b border-brand-dark/10 bg-white/70"><div className="mx-auto grid max-w-7xl divide-y divide-brand-dark/10 px-5 sm:grid-cols-3 sm:divide-x sm:divide-y-0 sm:px-8 lg:px-12"><div className="py-7 sm:pr-8"><p className="font-display text-3xl font-semibold text-brand-dark">8.405</p><p className="mt-1 text-sm text-text-muted">titulares documentados en el dossier institucional</p></div><div className="py-7 sm:px-8"><p className="font-display text-3xl font-semibold text-brand-dark">54.692</p><p className="mt-1 text-sm text-text-muted">beneficiarios documentados</p></div><div className="py-7 sm:pl-8"><p className="font-display text-3xl font-semibold text-brand-dark">21</p><p className="mt-1 text-sm text-text-muted">documentos institucionales vigentes en el Centro Legal</p></div></div></section>
  <EditorialSection><div className="grid gap-14 lg:grid-cols-[.8fr_1.2fr]"><SectionIntro eyebrow="Qué es ASODEF" title="Una organización que conecta relaciones y canales" description="La experiencia pública permite comprender el portafolio y encontrar una ruta. Los módulos especializados ejecutan pagos, solicitudes, seguimiento comercial y gestión de cuenta."/><div className="grid gap-4 sm:grid-cols-2"><article className="rounded-3xl bg-brand-deep p-7 text-white shadow-e3"><Network className="h-7 w-7 text-brand-orange-light"/><h3 className="mt-7 font-display text-2xl font-semibold">Conexión</h3><p className="mt-3 leading-7 text-white/70">Personas, afiliados, empresas y aliados acceden a recorridos distintos dentro del mismo sistema.</p></article><article className="surface-panel rounded-3xl p-7"><ShieldCheck className="h-7 w-7 text-brand-orange"/><h3 className="mt-7 font-display text-2xl font-semibold">Evidencia</h3><p className="mt-3 leading-7 text-text-muted">Consentimientos, versiones legales, auditoría y referencias conservan contexto de cada acción.</p></article></div></div></EditorialSection>
  <EditorialSection tone="soft"><SectionIntro eyebrow="Elige tu relación" title="Una entrada distinta para cada perfil" description="No obligamos a todas las personas a recorrer el mismo formulario."/><div className="mt-12 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{AUDIENCES.map(a=>{const Icon=audienceIcons[a.slug]; return <Link key={a.slug} to={`/soluciones/${a.slug}`} className="group flex flex-col rounded-3xl bg-white p-7 shadow-e1 transition hover:-translate-y-1 hover:shadow-e3"><Icon className="h-7 w-7 text-brand-orange"/><h3 className="mt-7 font-display text-2xl font-semibold">{a.title}</h3><p className="mt-3 flex-1 leading-7 text-text-muted">{a.summary}</p><span className="mt-6 inline-flex items-center gap-2 font-semibold text-brand-dark">Ver solución<ArrowRight className="h-4 w-4 transition group-hover:translate-x-1"/></span></Link>})}</div></EditorialSection>
  <EditorialSection><div className="flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><SectionIntro eyebrow="Portafolio" title="Beneficios organizados para decidir" description="Categorías verificadas, con proceso, límites y fuentes. Sin precios, coberturas ni garantías generales inventadas."/><Link to="/beneficios" className="public-button-secondary shrink-0">Ver las {BENEFITS.length} categorías<ArrowRight className="h-4 w-4"/></Link></div><div className="mt-12 grid gap-x-8 border-y border-brand-dark/10 md:grid-cols-2">{BENEFITS.slice(0,6).map((b,i)=><Link to={`/beneficios/${b.slug}`} key={b.slug} className="group flex items-center justify-between gap-5 border-b border-brand-dark/10 py-6 last:border-0 md:[&:nth-last-child(-n+2)]:border-b-0"><div><span className="text-xs font-bold text-brand-orange">0{i+1}</span><h3 className="mt-2 font-display text-xl font-semibold">{b.title}</h3><p className="mt-2 text-sm leading-6 text-text-muted">{b.summary}</p></div><ArrowRight className="h-5 w-5 shrink-0 text-brand-dark transition group-hover:translate-x-1"/></Link>)}</div></EditorialSection>
  <EditorialSection tone="dark"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-brand-orange-light">Cómo funciona</p><h2 className="mt-4 font-display text-4xl font-semibold tracking-tight sm:text-5xl">Del contexto al canal correcto</h2><p className="mt-5 text-lg leading-8 text-white/70">La plataforma reduce saltos y conserva la especialización de cada proceso.</p></div><NumberedProcess items={["Identifica tu perfil y necesidad sin entregar información innecesaria.", "Revisa el beneficio, portal o proceso que corresponde a tu caso.", "Continúa en el módulo especializado y conserva la referencia de la gestión."]}/></div></EditorialSection>
  <EditorialSection><div className="grid gap-5 lg:grid-cols-3"><article className="rounded-[2rem] border border-brand-dark/10 bg-white p-8 shadow-e2 lg:col-span-2"><HeartHandshake className="h-8 w-8 text-brand-orange"/><h2 className="mt-8 font-display text-3xl font-semibold">Empresas y potenciales aliados</h2><p className="mt-4 max-w-2xl leading-7 text-text-muted">Presentan una necesidad organizacional o una propuesta; el envío crea seguimiento real en CRM, sin conceder acceso ni confirmar una relación contractual.</p><Link className="public-button-primary mt-7" to="/soluciones/empresas">Conocer la ruta empresarial<ArrowRight className="h-4 w-4"/></Link></article><div className="grid gap-5"><Link to="/pagos" className="rounded-3xl bg-bg-soft p-6"><CreditCard className="h-6 w-6 text-brand-dark"/><h3 className="mt-5 font-display text-xl font-semibold">Consultar un pago</h3><p className="mt-2 text-sm leading-6 text-text-muted">Obligaciones, orden, Bold y comprobante.</p></Link><Link to="/recursos" className="rounded-3xl bg-bg-soft p-6"><FileText className="h-6 w-6 text-brand-dark"/><h3 className="mt-5 font-display text-xl font-semibold">Gestionar una solicitud</h3><p className="mt-2 text-sm leading-6 text-text-muted">PQR, datos personales y orientación.</p></Link></div></div></EditorialSection>
  <EditorialSection tone="soft"><div className="grid items-center gap-12 lg:grid-cols-2"><SectionIntro eyebrow="Confianza institucional" title="La protección de datos forma parte del recorrido" description="La autorización requerida se separa de las preferencias comerciales; cada aceptación puede vincularse con el documento legal vigente."/><div className="grid gap-3"><Link className="rounded-2xl border border-brand-dark/10 bg-white p-5 font-semibold text-brand-dark" to="/legal/tratamiento-de-datos">Política de tratamiento de datos</Link><Link className="rounded-2xl border border-brand-dark/10 bg-white p-5 font-semibold text-brand-dark" to="/legal/politica-de-privacidad">Política de privacidad</Link><Link className="rounded-2xl border border-brand-dark/10 bg-white p-5 font-semibold text-brand-dark" to="/legal">21 documentos institucionales vigentes</Link></div></div></EditorialSection>
  <PageCta title="Empieza por tu necesidad, no por un formulario genérico" description="El recorrido guiado te conduce a beneficios, pagos, PQR, solicitudes de datos, portales o seguimiento institucional." />
  </>;
}
