export type AudienceSlug = "personas" | "afiliados" | "empresas" | "aliados";

export interface AudienceDefinition {
  slug: AudienceSlug;
  title: string;
  summary: string;
  needs: string[];
  workflows: { title: string; description: string; to: string }[];
  portals: { label: string; to: string }[];
  considerations: string[];
  faq: { question: string; answer: string }[];
}

export const AUDIENCES = [
  { slug: "personas", title: "Personas y familias", summary: "Descubre el portafolio, recibe orientación y usa los canales públicos de pagos, PQR y datos personales.", needs: ["Explorar beneficios por necesidad", "Encontrar el canal correcto", "Gestionar una solicitud o un pago"], workflows: [{ title: "Conocer beneficios", description: "Filtra el portafolio por necesidad y revisa sus condiciones.", to: "/beneficios" }, { title: "Recibir orientación", description: "Usa el recorrido guiado para encontrar el siguiente paso.", to: "/comenzar" }, { title: "Canales formales", description: "Radica una PQR o una solicitud sobre datos personales.", to: "/recursos" }], portals: [{ label: "Centro de pagos", to: "/pagos" }, { label: "Ingresar", to: "/iniciar-sesion" }], considerations: ["Solo se solicitan los datos necesarios para la ruta elegida.", "Los beneficios dependen de la vinculación y las condiciones específicas informadas."], faq: [{ question: "¿Necesito una cuenta para conocer los beneficios?", answer: "No. Puedes explorar el portafolio público; algunas gestiones requieren autenticación o validación de la vinculación." }] },
  { slug: "afiliados", title: "Afiliados y usuarios", summary: "Consulta beneficios, gestiona tu cuenta y conserva evidencia de pagos, documentos y consentimientos.", needs: ["Acceder al portal personal", "Consultar condiciones asociadas", "Gestionar consentimientos y solicitudes"], workflows: [{ title: "Portal personal", description: "Accede a tu información y a las funciones habilitadas para tu cuenta.", to: "/mi-cuenta" }, { title: "Beneficios", description: "Identifica categorías relacionadas con tu necesidad.", to: "/beneficios?audiencia=afiliados" }, { title: "Pagos", description: "Consulta obligaciones y comprobantes por la ruta segura.", to: "/pagos" }], portals: [{ label: "Mi cuenta", to: "/mi-cuenta" }, { label: "Centro Legal", to: "/legal" }], considerations: ["El acceso requiere autenticación y está limitado a la cuenta correspondiente.", "Las aceptaciones se relacionan con la versión legal vigente al momento de la acción."], faq: [{ question: "¿Dónde consulto mis consentimientos?", answer: "En Mi cuenta, dentro de la sección Mis consentimientos disponible para usuarios autenticados." }] },
  { slug: "empresas", title: "Empresas", summary: "Conoce la vinculación institucional y las capacidades de gestión disponibles para representantes autorizados.", needs: ["Presentar una necesidad organizacional", "Gestionar la relación empresarial", "Acceder al portal con permisos"], workflows: [{ title: "Orientación empresarial", description: "Describe la necesidad y crea un registro real para seguimiento del equipo.", to: "/comenzar?perfil=empresa" }, { title: "Portal empresarial", description: "Acceso restringido a representantes con rol autorizado.", to: "/empresa" }, { title: "Protección de datos", description: "Consulta las condiciones del portal y el tratamiento aplicable.", to: "/legal/condiciones-portal-empresarial" }], portals: [{ label: "Portal empresarial", to: "/empresa" }, { label: "Contacto", to: "/contacto" }], considerations: ["El acceso empresarial aplica RBAC y no concede permisos por enviar un formulario.", "NIT y datos organizacionales se solicitan solo cuando son necesarios para la gestión."], faq: [{ question: "¿Enviar una solicitud crea acceso al portal?", answer: "No. La solicitud crea un registro para seguimiento; el acceso se habilita mediante el proceso autorizado correspondiente." }] },
  { slug: "aliados", title: "Potenciales aliados", summary: "Presenta una propuesta verificable para que ASODEF evalúe una relación comercial o de beneficios.", needs: ["Describir una oferta o capacidad", "Definir la audiencia relevante", "Crear seguimiento en CRM"], workflows: [{ title: "Presentar interés", description: "Registra los datos mínimos para evaluación y seguimiento.", to: "/comenzar?perfil=aliado" }, { title: "Conocer el portafolio", description: "Ubica las categorías institucionales con las que podría existir afinidad.", to: "/beneficios" }, { title: "Comunicaciones", description: "Define de forma independiente preferencias de correo y WhatsApp.", to: "/legal/politica-comunicaciones-electronicas" }], portals: [{ label: "Comenzar", to: "/comenzar?perfil=aliado" }, { label: "Información empresarial", to: "/legal/informacion-empresarial" }], considerations: ["No se afirma la existencia de un programa automático de aliados.", "Una postulación no constituye contrato, aprobación ni garantía de vinculación."], faq: [{ question: "¿El envío confirma una alianza?", answer: "No. Permite que ASODEF registre y evalúe el interés; cualquier relación requiere el proceso y la documentación aplicables." }] },
] as const satisfies readonly AudienceDefinition[];

export function getAudience(slug: string) { return AUDIENCES.find((audience) => audience.slug === slug); }
