export type AudienceSlug = "personas" | "afiliados" | "empresas" | "aliados";

export interface AudienceDefinition {
  slug: AudienceSlug;
  title: string;
  summary: string;
  heroActions: readonly [
    { label: string; to: string; primary: true },
    { label: string; to: string },
  ];
  needs: string[];
  workflows: { title: string; description: string; to: string }[];
  portals: { label: string; to: string }[];
  considerations: string[];
  faq: { question: string; answer: string }[];
}

export const AUDIENCES = [
  { slug: "personas", title: "Personas y familias", summary: "Consulta beneficios, pagos, PQR y solicitudes sobre datos personales sin una credencial administrativa.", heroActions: [{ label: "Consultar beneficios", to: "/beneficios", primary: true }, { label: "Recibir orientación", to: "/comenzar" }], needs: ["Explorar beneficios por necesidad", "Encontrar el servicio aplicable", "Gestionar una solicitud o un pago"], workflows: [{ title: "Conocer beneficios", description: "Filtra el portafolio por necesidad y revisa sus condiciones.", to: "/beneficios" }, { title: "Consultar mi afiliación", description: "Inicia la verificación con número de titular o documento.", to: "/mi-cuenta/acceso" }, { title: "Presentar una solicitud", description: "Radica una PQR o ejerce un derecho sobre tus datos.", to: "/recursos" }], portals: [{ label: "Centro de pagos", to: "/pagos" }, { label: "Consultar mi afiliación", to: "/mi-cuenta/acceso" }], considerations: ["Solo se solicitan los datos necesarios para la acción elegida.", "Los beneficios dependen de la vinculación y las condiciones específicas informadas."], faq: [{ question: "¿Necesito una contraseña para conocer los beneficios?", answer: "No. Puedes explorar el portafolio público; para datos personales debes verificar tu identidad por el canal registrado." }] },
  { slug: "afiliados", title: "Afiliados y titulares", summary: "Inicia con tu número de titular o documento y verifica tu identidad antes de consultar información personal.", heroActions: [{ label: "Consultar mi afiliación", to: "/mi-cuenta/acceso", primary: true }, { label: "Consultar beneficios", to: "/beneficios?audiencia=afiliados" }], needs: ["Consultar la afiliación", "Consultar y actualizar beneficiarios mediante solicitudes", "Cargar documentos de soporte", "Consultar el estado de cuenta", "Pagar obligaciones", "Consultar pagos y comprobantes", "Consultar documentos", "Seguir solicitudes"], workflows: [{ title: "Consultar mi afiliación", description: "Empieza con número de titular o documento y completa la verificación requerida.", to: "/mi-cuenta/acceso" }, { title: "Beneficiarios y documentos", description: "Consulta beneficiarios y radica solicitudes de adición, actualización o retiro.", to: "/mi-cuenta/beneficiarios" }, { title: "Estado de cuenta y pagos", description: "Consulta obligaciones, pagos y comprobantes disponibles para tu vinculación.", to: "/mi-cuenta/estado-de-cuenta" }], portals: [{ label: "Acceso de afiliados", to: "/mi-cuenta/acceso" }, { label: "Centro de pagos", to: "/pagos" }], considerations: ["El identificador solo inicia la consulta; la información sensible exige un código enviado a un contacto registrado.", "Los cambios de beneficiarios se procesan como solicitudes y no alteran directamente el registro maestro."], faq: [{ question: "¿Debo usar correo y contraseña?", answer: "No. Inicia con número de titular o documento y completa la verificación habilitada para tu registro." }] },
  { slug: "empresas", title: "Empresas", summary: "Inicia con el NIT registrado para consultar la relación organizacional y los recursos empresariales habilitados.", heroActions: [{ label: "Acceso de empresas", to: "/empresa/acceso", primary: true }, { label: "Solicitar orientación", to: "/comenzar?perfil=empresa" }], needs: ["Consultar la relación organizacional", "Consultar beneficios y contratos", "Revisar pagos, documentos, solicitudes y reportes autorizados"], workflows: [{ title: "Relación y beneficios", description: "Verifica la empresa con su NIT y consulta la información habilitada.", to: "/empresa/acceso" }, { title: "Contratos y documentos", description: "Consulta referencias contractuales y documentos entregados por el proveedor.", to: "/empresa/contratos" }, { title: "Pagos y solicitudes", description: "Revisa pagos disponibles y sigue solicitudes empresariales.", to: "/empresa/pagos" }], portals: [{ label: "Acceso de empresas", to: "/empresa/acceso" }, { label: "Solicitar orientación", to: "/comenzar?perfil=empresa" }], considerations: ["El NIT solo inicia la consulta; los datos empresariales requieren verificación por un canal registrado.", "Enviar una solicitud de orientación no concede acceso al portal."], faq: [{ question: "¿La empresa necesita correo y contraseña?", answer: "No. El acceso comienza con el NIT registrado y continúa con la verificación habilitada para la organización." }] },
  { slug: "aliados", title: "Potenciales aliados", summary: "Presenta una propuesta para evaluación comercial y seguimiento por ASODEF.", heroActions: [{ label: "Presentar interés", to: "/comenzar?perfil=aliado", primary: true }, { label: "Conocer el portafolio", to: "/beneficios" }], needs: ["Describir una oferta o capacidad", "Definir la audiencia relevante", "Crear seguimiento en CRM"], workflows: [{ title: "Presentar interés", description: "Registra los datos mínimos para evaluación y seguimiento.", to: "/comenzar?perfil=aliado" }, { title: "Conocer el portafolio", description: "Consulta las categorías relacionadas con tu propuesta.", to: "/beneficios" }, { title: "Comunicaciones", description: "Define por separado tus preferencias de correo y WhatsApp.", to: "/legal/politica-comunicaciones-electronicas" }], portals: [{ label: "Presentar propuesta", to: "/comenzar?perfil=aliado" }, { label: "Información empresarial", to: "/legal/informacion-empresarial" }], considerations: ["No se afirma la existencia de un programa automático de aliados.", "Una postulación no constituye contrato, aprobación ni garantía de vinculación."], faq: [{ question: "¿El envío confirma una alianza?", answer: "No. Permite que ASODEF registre y evalúe el interés; cualquier relación requiere el proceso y la documentación aplicables." }] },
] as const satisfies readonly AudienceDefinition[];

export function getAudience(slug: string) { return AUDIENCES.find((audience) => audience.slug === slug); }
