export type AudienceSlug = "personas" | "afiliados" | "empresas" | "aliados";

export interface AudienceDefinition {
  slug: AudienceSlug;
  title: string;
  summary: string;
  needs: string[];
  workflows: { title: string; description: string; to: string }[];
  portals: { label: string; to: string }[];
  considerations: string[];
  faq: { question: string; answer: string }[];
}

export const AUDIENCES = [
  { slug: "personas", title: "Personas y familias", summary: "Consulta beneficios, pagos, PQR y solicitudes sobre datos personales sin necesidad de una cuenta.", needs: ["Explorar beneficios por necesidad", "Encontrar el servicio aplicable", "Gestionar una solicitud o un pago"], workflows: [{ title: "Conocer beneficios", description: "Filtra el portafolio por necesidad y revisa sus condiciones.", to: "/beneficios" }, { title: "Recibir orientación", description: "Indica qué necesitas y abre el servicio correspondiente.", to: "/comenzar" }, { title: "Presentar una solicitud", description: "Radica una PQR o ejerce un derecho sobre tus datos.", to: "/recursos" }], portals: [{ label: "Centro de pagos", to: "/pagos" }, { label: "Ingresar", to: "/iniciar-sesion" }], considerations: ["Solo se solicitan los datos necesarios para la acción elegida.", "Los beneficios dependen de la vinculación y las condiciones específicas informadas."], faq: [{ question: "¿Necesito una cuenta para conocer los beneficios?", answer: "No. Puedes explorar el portafolio público; algunas gestiones requieren autenticación o validación de la vinculación." }] },
  { slug: "afiliados", title: "Afiliados y usuarios", summary: "Consulta beneficios y pagos, entra a tu cuenta y administra tus consentimientos.", needs: ["Acceder al portal personal", "Consultar condiciones asociadas", "Gestionar consentimientos y solicitudes"], workflows: [{ title: "Portal personal", description: "Accede a las funciones habilitadas para tu cuenta.", to: "/mi-cuenta" }, { title: "Beneficios", description: "Consulta categorías disponibles para afiliados.", to: "/beneficios?audiencia=afiliados" }, { title: "Pagos", description: "Consulta obligaciones y comprobantes.", to: "/pagos" }], portals: [{ label: "Mi cuenta", to: "/mi-cuenta" }, { label: "Centro Legal", to: "/legal" }], considerations: ["El acceso requiere autenticación y está limitado a la cuenta correspondiente.", "Las aceptaciones se relacionan con la versión legal vigente al momento de la acción."], faq: [{ question: "¿Dónde consulto mis consentimientos?", answer: "En Mi cuenta, dentro de la sección Mis consentimientos disponible para usuarios autenticados." }] },
  { slug: "empresas", title: "Empresas", summary: "Solicita orientación empresarial o accede al portal con un rol de representante autorizado.", needs: ["Presentar una necesidad organizacional", "Gestionar la relación empresarial", "Acceder al portal con permisos"], workflows: [{ title: "Orientación empresarial", description: "Describe la necesidad y crea un registro para seguimiento.", to: "/comenzar?perfil=empresa" }, { title: "Portal empresarial", description: "Acceso restringido a representantes autorizados.", to: "/empresa" }, { title: "Protección de datos", description: "Consulta las condiciones del portal y el tratamiento aplicable.", to: "/legal/condiciones-portal-empresarial" }], portals: [{ label: "Portal empresarial", to: "/empresa" }, { label: "Contacto", to: "/contacto" }], considerations: ["Enviar un formulario no concede acceso ni permisos empresariales.", "NIT y datos organizacionales se solicitan solo cuando son necesarios para la gestión."], faq: [{ question: "¿Enviar una solicitud crea acceso al portal?", answer: "No. La solicitud crea un registro para seguimiento; el acceso se habilita mediante el proceso autorizado correspondiente." }] },
  { slug: "aliados", title: "Potenciales aliados", summary: "Presenta una propuesta para evaluación comercial y seguimiento por ASODEF.", needs: ["Describir una oferta o capacidad", "Definir la audiencia relevante", "Crear seguimiento en CRM"], workflows: [{ title: "Presentar interés", description: "Registra los datos mínimos para evaluación y seguimiento.", to: "/comenzar?perfil=aliado" }, { title: "Conocer el portafolio", description: "Consulta las categorías relacionadas con tu propuesta.", to: "/beneficios" }, { title: "Comunicaciones", description: "Define por separado tus preferencias de correo y WhatsApp.", to: "/legal/politica-comunicaciones-electronicas" }], portals: [{ label: "Presentar propuesta", to: "/comenzar?perfil=aliado" }, { label: "Información empresarial", to: "/legal/informacion-empresarial" }], considerations: ["No se afirma la existencia de un programa automático de aliados.", "Una postulación no constituye contrato, aprobación ni garantía de vinculación."], faq: [{ question: "¿El envío confirma una alianza?", answer: "No. Permite que ASODEF registre y evalúe el interés; cualquier relación requiere el proceso y la documentación aplicables." }] },
] as const satisfies readonly AudienceDefinition[];

export function getAudience(slug: string) { return AUDIENCES.find((audience) => audience.slug === slug); }
