export type BenefitAudience = "personas" | "afiliados" | "empresas" | "aliados";
export type BenefitNeed = "proteccion" | "salud" | "orientacion" | "movilidad" | "educacion" | "ahorro";

export interface BenefitDefinition {
  id: string;
  slug: string;
  title: string;
  summary: string;
  audience: BenefitAudience[];
  needs: BenefitNeed[];
  problem: string;
  outcome: string;
  capabilities: string[];
  eligibility: string;
  process: string[];
  requiredInformation: string[];
  faq: { question: string; answer: string }[];
  relatedSlugs: string[];
  legalSlugs: string[];
  sourceBasis: string;
  seo: { title: string; description: string };
}

const commonEligibility = "La disponibilidad y las condiciones aplicables dependen de la vinculación vigente y de la información presentada para el beneficio específico.";

export const BENEFITS = [
  { id: "funeral", slug: "plan-exequial-familiar", title: "Plan exequial familiar", summary: "Orientación y acceso a la protección exequial asociada a la vinculación aplicable.", audience: ["afiliados", "personas"], needs: ["proteccion"], problem: "Contar con una ruta clara de orientación ante una necesidad exequial familiar.", outcome: "Identificar el canal y las condiciones que corresponden a la vinculación del titular.", capabilities: ["Consulta de información asociada", "Orientación por los canales institucionales", "Gestión de solicitudes y soportes"], eligibility: commonEligibility, process: ["Identifica tu relación con ASODEF.", "Consulta las condiciones aplicables a tu vinculación.", "Usa el canal indicado para solicitar orientación o gestionar el caso."], requiredInformation: ["Identificación del titular", "Datos de contacto", "Información del caso cuando sea necesaria"], faq: [{ question: "¿La página define coberturas?", answer: "No. La cobertura aplicable es la informada en la vinculación o documento específico aceptado por el titular." }], relatedSlugs: ["seguro-de-vida", "asesoria-juridica"], legalSlugs: ["terminos-y-condiciones", "politica-de-privacidad"], sourceBasis: "Dossier institucional y flujos de afiliado, contratos, solicitudes y atención implementados.", seo: { title: "Plan exequial familiar | ASODEF", description: "Conoce la ruta de orientación de ASODEF para consultar la protección exequial familiar asociada a una vinculación vigente." } },
  { id: "life", slug: "seguro-de-vida", title: "Seguro de vida", summary: "Información y orientación sobre la protección de vida vinculada al titular.", audience: ["afiliados", "personas"], needs: ["proteccion"], problem: "Comprender cómo consultar una protección de vida relacionada con la vinculación.", outcome: "Acceder al canal que permite verificar las condiciones aplicables.", capabilities: ["Orientación institucional", "Consulta de documentos relacionados", "Canal formal para solicitudes"], eligibility: commonEligibility, process: ["Verifica tu calidad de titular o beneficiario.", "Consulta los documentos de tu relación.", "Solicita orientación cuando la información requiera validación."], requiredInformation: ["Identificación", "Relación con el titular", "Datos de contacto"], faq: [{ question: "¿ASODEF publica valores asegurados?", answer: "No se presentan valores generales. Los valores y condiciones son los que constan en la relación específica aplicable." }], relatedSlugs: ["plan-exequial-familiar", "salud-y-bienestar"], legalSlugs: ["condiciones-portal-afiliado", "tratamiento-de-datos"], sourceBasis: "Dossier institucional y gestión documental/contractual existente.", seo: { title: "Seguro de vida | ASODEF", description: "Consulta la ruta de ASODEF para orientarte sobre la protección de vida vinculada a tu relación específica." } },
  { id: "legal", slug: "asesoria-juridica", title: "Asesoría jurídica", summary: "Ruta para conocer la orientación jurídica disponible dentro del portafolio.", audience: ["afiliados", "personas"], needs: ["orientacion"], problem: "Ubicar un canal de orientación para una necesidad jurídica.", outcome: "Conocer el proceso y las condiciones comunicadas para el caso concreto.", capabilities: ["Clasificación inicial de la necesidad", "Orientación al canal correspondiente", "Radicación formal cuando aplique"], eligibility: commonEligibility, process: ["Describe brevemente la necesidad.", "ASODEF identifica el canal aplicable.", "Consulta las condiciones antes de continuar."], requiredInformation: ["Tema general de consulta", "Datos de contacto", "Soportes solo cuando sean requeridos"], faq: [{ question: "¿La orientación reemplaza una representación legal?", answer: "No se afirma una representación general. El alcance aplicable debe informarse antes de aceptar un servicio específico." }], relatedSlugs: ["educacion", "plan-exequial-familiar"], legalSlugs: ["terminos-y-condiciones", "aviso-de-privacidad"], sourceBasis: "Dossier institucional y flujos PQR/contacto implementados.", seo: { title: "Asesoría jurídica | ASODEF", description: "Conoce cómo solicitar orientación sobre la categoría de asesoría jurídica del portafolio ASODEF." } },
  { id: "mobility", slug: "movilidad", title: "Movilidad", summary: "Convenios informados para necesidades de vehículo, CDA, repuestos y servicios.", audience: ["afiliados", "personas"], needs: ["movilidad", "ahorro"], problem: "Encontrar opciones del portafolio relacionadas con movilidad.", outcome: "Identificar alternativas y verificar su condición vigente antes de usarlas.", capabilities: ["Descubrimiento de categorías", "Orientación de acceso", "Verificación de condición específica"], eligibility: commonEligibility, process: ["Selecciona la necesidad de movilidad.", "Consulta la alternativa disponible.", "Verifica condiciones con el canal informado."], requiredInformation: ["Tipo de necesidad", "Calidad de afiliado cuando aplique"], faq: [{ question: "¿Todos los establecimientos tienen las mismas condiciones?", answer: "No. Cada alternativa puede tener condiciones propias que deben consultarse antes de usarla." }], relatedSlugs: ["convenios-comerciales", "salud-y-bienestar"], legalSlugs: ["terminos-y-condiciones"], sourceBasis: "Dossier institucional: CDA, repuestos, accesorios y servicios para vehículo.", seo: { title: "Beneficios de movilidad | ASODEF", description: "Explora la categoría de movilidad del portafolio ASODEF y verifica la alternativa aplicable a tu vinculación." } },
  { id: "wellbeing", slug: "salud-y-bienestar", title: "Salud y bienestar", summary: "Acceso orientado a categorías de farmacias, diagnóstico, óptica y bienestar.", audience: ["afiliados", "personas"], needs: ["salud", "ahorro"], problem: "Encontrar alternativas del portafolio para necesidades cotidianas de salud y bienestar.", outcome: "Consultar opciones y condiciones vigentes sin confundirlas con atención médica de urgencia.", capabilities: ["Exploración por necesidad", "Orientación al canal", "Consulta de condiciones"], eligibility: commonEligibility, process: ["Selecciona la categoría que necesitas.", "Consulta la alternativa informada.", "Confirma vigencia y condiciones antes de acceder."], requiredInformation: ["Necesidad general", "Datos de vinculación cuando sean requeridos"], faq: [{ question: "¿Este canal atiende urgencias médicas?", answer: "No. Ante una urgencia debes acudir a los servicios de emergencia correspondientes." }], relatedSlugs: ["convenios-comerciales", "educacion"], legalSlugs: ["tratamiento-datos-sensibles", "aviso-de-privacidad"], sourceBasis: "Dossier institucional: farmacias, imágenes diagnósticas, ópticas y salud visual.", seo: { title: "Salud y bienestar | ASODEF", description: "Conoce las categorías de salud y bienestar del portafolio ASODEF y cómo consultar sus condiciones." } },
  { id: "education", slug: "educacion", title: "Educación", summary: "Opciones informadas para útiles, papelería y convenios educativos.", audience: ["afiliados", "personas"], needs: ["educacion", "ahorro"], problem: "Ubicar alternativas que apoyen necesidades educativas del grupo familiar.", outcome: "Conocer las categorías disponibles y el proceso de consulta.", capabilities: ["Información por categoría", "Orientación de acceso", "Consulta de vigencia"], eligibility: commonEligibility, process: ["Define la necesidad educativa.", "Revisa la alternativa relacionada.", "Verifica la condición aplicable antes de continuar."], requiredInformation: ["Tipo de necesidad", "Vinculación cuando aplique"], faq: [{ question: "¿Se garantizan cupos o tarifas?", answer: "No. La disponibilidad y el valor dependen de la alternativa específica y deben informarse antes de la aceptación." }], relatedSlugs: ["convenios-comerciales", "salud-y-bienestar"], legalSlugs: ["terminos-y-condiciones"], sourceBasis: "Dossier institucional: papelería, útiles y convenios educativos.", seo: { title: "Beneficios de educación | ASODEF", description: "Consulta las categorías educativas del portafolio ASODEF y la ruta para conocer condiciones vigentes." } },
  { id: "commerce", slug: "convenios-comerciales", title: "Convenios comerciales", summary: "Categorías de comercios y servicios que pueden ofrecer condiciones para la comunidad vinculada.", audience: ["afiliados", "personas", "empresas", "aliados"], needs: ["ahorro"], problem: "Descubrir alternativas comerciales relevantes sin asumir que todas tienen las mismas condiciones.", outcome: "Conectar la necesidad con una categoría y consultar la alternativa vigente.", capabilities: ["Exploración por categoría", "Relación con aliados", "Orientación comercial"], eligibility: commonEligibility, process: ["Selecciona una categoría.", "Consulta la información disponible.", "Confirma la condición específica antes de usarla."], requiredInformation: ["Categoría de interés", "Relación con ASODEF cuando aplique"], faq: [{ question: "¿La publicación garantiza un descuento?", answer: "No. Cada condición debe estar vigente y ser comunicada para el establecimiento o relación específica." }], relatedSlugs: ["movilidad", "salud-y-bienestar", "educacion"], legalSlugs: ["terminos-y-condiciones", "politica-comunicaciones-electronicas"], sourceBasis: "Dossier institucional y modelos CRM de empresas/aliados.", seo: { title: "Convenios comerciales | ASODEF", description: "Explora categorías de convenios comerciales y conoce cómo validar las condiciones aplicables en ASODEF." } },
  { id: "complementary", slug: "categorias-complementarias", title: "Categorías complementarias", summary: "Veterinarias, supermercados, restaurantes, gimnasios y turismo dentro del portafolio informado.", audience: ["afiliados", "personas", "aliados"], needs: ["ahorro", "salud"], problem: "Encontrar categorías complementarias relevantes para la vida familiar.", outcome: "Conocer su existencia en el portafolio y pedir información vigente.", capabilities: ["Descubrimiento de categorías", "Orientación comercial", "Consulta de vigencia"], eligibility: commonEligibility, process: ["Elige la categoría de interés.", "Solicita orientación si no encuentras una alternativa publicada.", "Revisa las condiciones informadas antes de aceptarlas."], requiredInformation: ["Categoría de interés", "Ciudad solo cuando sea operacionalmente relevante"], faq: [{ question: "¿La disponibilidad es igual en todas las ciudades?", answer: "No se presume. La disponibilidad debe verificarse para la alternativa y ubicación correspondientes." }], relatedSlugs: ["convenios-comerciales", "salud-y-bienestar"], legalSlugs: ["terminos-y-condiciones", "aviso-de-privacidad"], sourceBasis: "Dossier institucional: veterinarias, supermercados, restaurantes, gimnasios y turismo.", seo: { title: "Categorías complementarias | ASODEF", description: "Conoce las categorías complementarias documentadas en el portafolio institucional de ASODEF." } },
] as const satisfies readonly BenefitDefinition[];

export function getBenefit(slug: string) { return BENEFITS.find((benefit) => benefit.slug === slug); }
