import { Link } from "react-router-dom";
import { PageHeader } from "@asodef/ui";
import { ContactUpdatePanel, SelfServiceCollectionSection, SelfServiceResourcePage, SelfServiceStatePanel } from "../../components/self-service";
import { selfServiceApi } from "../../lib/self-service";

const AFFILIATE = "Mi cuenta · Afiliados";

export function AffiliateSummaryPage() { return <SelfServiceResourcePage queryKey={["self-service", "affiliate", "summary"]} queryFn={(signal) => selfServiceApi.getSummary("affiliate", signal)} title="Resumen" description="Consulta el estado que entrega el proveedor autorizado para tu relación con ASODEF." eyebrow={AFFILIATE} />; }
export function AffiliateAffiliationPage() { return <div className="space-y-8"><SelfServiceResourcePage queryKey={["self-service", "affiliate", "affiliation"]} queryFn={selfServiceApi.getAffiliateAffiliation} title="Mi afiliación" description="Revisa la información vigente de tu afiliación." eyebrow={AFFILIATE} /><ContactUpdatePanel /></div>; }
export function AffiliateBeneficiariesPage() { return <SelfServiceResourcePage queryKey={["self-service", "affiliate", "beneficiaries"]} queryFn={selfServiceApi.getAffiliateBeneficiaries} title="Beneficiarios" description="Consulta beneficiarios y radica cambios sujetos a las reglas del proveedor." eyebrow={AFFILIATE} actions={<Link to="/mi-cuenta/beneficiarios/nueva-solicitud" className="inline-flex h-11 items-center rounded-full bg-brand-dark px-5 text-sm font-medium text-white">Nueva solicitud</Link>} />; }
export function AffiliateAccountStatementPage() { return <div className="space-y-8"><PageHeader title="Estado de cuenta" description="Consulta saldos, movimientos y obligaciones disponibles para tu registro." eyebrow={AFFILIATE} /><SelfServiceCollectionSection title="Estado de cuenta" description="Información consolidada a la fecha de corte informada por el proveedor." queryKey={["self-service", "affiliate", "statement"]} queryFn={selfServiceApi.getAffiliateStatement} /><SelfServiceCollectionSection title="Obligaciones" description="Conceptos pendientes o vigentes reportados para tu afiliación." queryKey={["self-service", "affiliate", "obligations"]} queryFn={(signal) => selfServiceApi.getRecords("affiliate", "obligations", signal)} /></div>; }
export function AffiliatePaymentsPage() { return <div className="space-y-8"><PageHeader title="Pagos y comprobantes" description="Revisa pagos y comprobantes reportados por el proveedor." eyebrow={AFFILIATE} actions={<Link to="/pagos" className="inline-flex h-11 items-center rounded-full bg-brand-dark px-5 text-sm font-medium text-white">Ir al centro de pagos</Link>} /><SelfServiceCollectionSection title="Pagos" description="Movimientos de pago disponibles para tu registro." queryKey={["self-service", "affiliate", "payments"]} queryFn={(signal) => selfServiceApi.getRecords("affiliate", "payments", signal)} /><SelfServiceCollectionSection title="Comprobantes" description="Comprobantes habilitados por el proveedor." queryKey={["self-service", "affiliate", "receipts"]} queryFn={(signal) => selfServiceApi.getRecords("affiliate", "receipts", signal)} /></div>; }
export function AffiliateDocumentsPage() { return <SelfServiceResourcePage queryKey={["self-service", "affiliate", "documents"]} queryFn={(signal) => selfServiceApi.getRecords("affiliate", "documents", signal)} title="Documentos" description="Consulta los documentos habilitados para tu registro." eyebrow={AFFILIATE} />; }
export function AffiliateRequestsPage() { return <SelfServiceResourcePage queryKey={["self-service", "affiliate", "requests"]} queryFn={(signal) => selfServiceApi.getRecords("affiliate", "requests", signal)} title="Solicitudes" description="Sigue las solicitudes registradas en el proveedor autorizado." eyebrow={AFFILIATE} />; }
export function AffiliateNotificationsPage() { return <div className="space-y-6"><PageHeader title="Notificaciones" description="Este espacio mostrará avisos cuando el proveedor habilite el servicio." eyebrow={AFFILIATE} /><SelfServiceStatePanel status="not_configured" message="El proveedor autorizado aún no expone un canal de notificaciones para el portal." /></div>; }
