/**
 * A static blocklist of extremely common / previously-breached passwords
 * (lowercased). This is intentionally a local, dependency-free list, not
 * a live call to a third-party breach-checking API (e.g. HaveIBeenPwned):
 * no outbound network dependency in the password-validation hot path,
 * and no third-party service ever sees a candidate password, even
 * k-anonymized. `PasswordPolicyService` is written against a small
 * `isCommonPassword()` seam specifically so a real breach-database
 * integration can be swapped in later without touching any calling code -
 * see PasswordPolicyService's doc comment.
 */
export const COMMON_PASSWORDS: ReadonlySet<string> = new Set(
  [
    "123456",
    "123456789",
    "12345678",
    "12345",
    "1234567",
    "1234567890",
    "qwerty",
    "qwerty123",
    "password",
    "password1",
    "password123",
    "111111",
    "123123",
    "abc123",
    "1q2w3e4r",
    "1qaz2wsx",
    "iloveyou",
    "admin",
    "administrator",
    "welcome",
    "welcome1",
    "monkey",
    "dragon",
    "letmein",
    "login",
    "princess",
    "solo",
    "starwars",
    "sunshine",
    "master",
    "hello",
    "hello123",
    "freedom",
    "whatever",
    "trustno1",
    "000000",
    "121212",
    "654321",
    "aaaaaa",
    "222222",
    "asdfgh",
    "asdf1234",
    "zxcvbnm",
    "qazwsx",
    "football",
    "baseball",
    "basketball",
    "superman",
    "batman",
    "shadow",
    "michael",
    "jennifer",
    "jordan",
    "hunter",
    "hunter2",
    "michelle",
    "charlie",
    "andrew",
    "daniel",
    "matthew",
    "computer",
    "internet",
    "changeme",
    "changeme123",
    "letmein123",
    "passw0rd",
    "p@ssword",
    "p@ssw0rd",
    "abcd1234",
    "abcdefgh",
    "1234abcd",
    "asodef",
    "asodef123",
    "colombia",
    "colombia123",
    "bienvenido",
    "bienvenida",
    "contraseña",
    "contrasena",
    "contrasena123",
    "12345678910",
    "qwertyuiop",
    "senha123",
  ].map((password) => password.toLowerCase()),
);
