import { useEffect, useRef, useState } from "react";
import { Link, NavLink, Outlet, useLocation } from "react-router-dom";
import { ASODEF_COMPANY } from "@asodef/config";
import { Drawer, IconButton } from "@asodef/ui";
import { ArrowRight, ChevronDown, LogIn, Menu, ShieldCheck, X } from "lucide-react";
import { PUBLIC_NAV_GROUPS, PUBLIC_ROUTES } from "../lib/public-content/public-routes";
import { useCookieConsent } from "../lib/cookie-consent/cookie-consent-context";
import { BrandLogo } from "./shared/BrandLogo";
import { SkipToContent } from "./shared/SkipToContent";
import { useFocusMainOnRouteChange } from "./shared/useFocusMainOnRouteChange";
import { useScrollToHash } from "./shared/useScrollToHash";
import { WhatsAppFloatingButton } from "./shared/WhatsAppFloatingButton";
import { RouteTransition } from "../components/public/motion";

const WHATSAPP_NUMBER = "573232733927";
const primary = [PUBLIC_ROUTES.about, PUBLIC_ROUTES.benefits, PUBLIC_ROUTES.solutions, PUBLIC_ROUTES.companies];

export function PublicLayout() {
  const mainRef = useRef<HTMLElement>(null);
  const menuRef = useRef<HTMLLIElement>(null);
  const hamburgerRef = useRef<HTMLButtonElement>(null);
  const location = useLocation();
  const { openPreferences } = useCookieConsent();
  const [scrolled, setScrolled] = useState(false);
  const [drawerOpen, setDrawerOpen] = useState(false);
  const [resourcesOpen, setResourcesOpen] = useState(false);
  const [mobileGroup, setMobileGroup] = useState<string>(PUBLIC_NAV_GROUPS[0]?.label ?? "");
  useFocusMainOnRouteChange(mainRef); useScrollToHash();

  useEffect(() => { const onScroll=()=>setScrolled(window.scrollY>8); onScroll(); window.addEventListener("scroll",onScroll,{passive:true}); return()=>window.removeEventListener("scroll",onScroll); },[]);
  useEffect(()=>{setDrawerOpen(false);setResourcesOpen(false); const routeGroup=PUBLIC_NAV_GROUPS.find(group=>group.items.some(item=>location.pathname===item.path||location.pathname.startsWith(`${item.path}/`))); if(routeGroup)setMobileGroup(routeGroup.label);},[location.pathname,location.hash]);
  useEffect(()=>{ if(!resourcesOpen)return; const onDown=(e:MouseEvent)=>{if(!menuRef.current?.contains(e.target as Node))setResourcesOpen(false)}; const onKey=(e:KeyboardEvent)=>{if(e.key==="Escape")setResourcesOpen(false)}; document.addEventListener("mousedown",onDown);document.addEventListener("keydown",onKey);return()=>{document.removeEventListener("mousedown",onDown);document.removeEventListener("keydown",onKey)};},[resourcesOpen]);
  const closeDrawer=()=>{setDrawerOpen(false);requestAnimationFrame(()=>hamburgerRef.current?.focus())};
  const focusMobileGroup=(index:number)=>{const count=PUBLIC_NAV_GROUPS.length;const normalized=(index+count)%count;const group=PUBLIC_NAV_GROUPS[normalized];if(!group)return;setMobileGroup(group.label);requestAnimationFrame(()=>document.getElementById(`mobile-nav-tab-${normalized}`)?.focus())};
  return <div className="flex min-h-screen flex-col overflow-x-clip bg-bg-base"><SkipToContent targetId="main-content"/>
    <header className={`sticky top-0 z-40 border-b transition ${scrolled?"border-brand-dark/10 bg-[#F4F5F1]/92 shadow-e2 backdrop-blur-2xl":"border-transparent bg-bg-base/80 backdrop-blur-xl"}`}><div className="mx-auto flex max-w-7xl items-center gap-5 px-5 py-3 sm:px-8 lg:px-12"><Link to="/" aria-label={`${ASODEF_COMPANY.legalName}, inicio`}><BrandLogo className="h-10 w-auto"/></Link>
      <nav aria-label="Principal" className="ml-auto hidden items-center lg:flex"><ul className="flex items-center gap-1"><li><NavLink to="/" end className={({isActive})=>`rounded-full px-3 py-2 text-sm font-semibold ${isActive?"bg-brand-dark/8 text-brand-dark":"text-text-muted hover:text-brand-dark"}`}>Inicio</NavLink></li>{primary.map(item=><li key={item.path}><NavLink to={item.path} className={({isActive})=>`rounded-full px-3 py-2 text-sm font-semibold ${isActive?"bg-brand-dark/8 text-brand-dark":"text-text-muted hover:text-brand-dark"}`}>{item.label}</NavLink></li>)}<li ref={menuRef} className="relative"><button aria-expanded={resourcesOpen} aria-controls="resource-menu" onClick={()=>setResourcesOpen(v=>!v)} className="flex items-center gap-1 rounded-full px-3 py-2 text-sm font-semibold text-text-muted hover:text-brand-dark">Recursos<ChevronDown className={`h-4 w-4 transition ${resourcesOpen?"rotate-180":""}`}/></button>{resourcesOpen&&<div id="resource-menu" className="absolute right-0 top-12 w-[34rem] rounded-3xl border border-brand-dark/10 bg-white p-4 shadow-e4"><div className="grid grid-cols-2 gap-2">{PUBLIC_NAV_GROUPS[2].items.map(item=><Link key={item.path} to={item.path} className="rounded-2xl p-4 hover:bg-bg-soft"><span className="font-semibold text-brand-dark">{item.label}</span><span className="mt-1 block text-xs leading-5 text-text-muted">{item.description}</span></Link>)}</div><div className="mt-2 grid grid-cols-3 gap-2 border-t border-brand-dark/10 pt-3">{[PUBLIC_ROUTES.payments,PUBLIC_ROUTES.pqr,PUBLIC_ROUTES.dsr].map(item=><Link key={item.path} to={item.path} className="rounded-xl px-3 py-2 text-xs font-semibold text-brand-dark hover:bg-bg-soft">{item.label}</Link>)}</div></div>}</li></ul></nav>
      <div className="hidden items-center gap-2 lg:flex"><Link to="/iniciar-sesion" className="public-button-secondary !min-h-10 !px-4"><LogIn className="h-4 w-4"/>Ingresar</Link><Link to="/comenzar" className="public-button-primary !min-h-10 !px-4">Recibir orientación<ArrowRight className="h-4 w-4"/></Link></div>
      <IconButton ref={hamburgerRef} aria-label="Abrir menú de navegación" icon={<Menu className="h-5 w-5"/>} className="ml-auto !h-12 !w-12 lg:hidden" onClick={()=>setDrawerOpen(true)}/></div></header>
    <Drawer open={drawerOpen} onClose={closeDrawer} title="Navegación" side="right"><div className="mb-5 flex items-center justify-between"><BrandLogo className="h-9 w-auto"/><button onClick={closeDrawer} aria-label="Cerrar menú" className="flex h-12 w-12 items-center justify-center rounded-full hover:bg-bg-soft"><X className="h-5 w-5"/></button></div><nav aria-label="Principal móvil"><div role="tablist" aria-label="Grupos de navegación" className="grid grid-cols-3 gap-1 rounded-2xl bg-bg-soft p-1">{PUBLIC_NAV_GROUPS.map((group,index)=><button key={group.label} id={`mobile-nav-tab-${index}`} type="button" role="tab" tabIndex={mobileGroup===group.label?0:-1} aria-selected={mobileGroup===group.label} aria-controls={`mobile-nav-panel-${index}`} onClick={()=>setMobileGroup(group.label)} onKeyDown={(event)=>{if(event.key==="ArrowRight"){event.preventDefault();focusMobileGroup(index+1)}else if(event.key==="ArrowLeft"){event.preventDefault();focusMobileGroup(index-1)}else if(event.key==="Home"){event.preventDefault();focusMobileGroup(0)}else if(event.key==="End"){event.preventDefault();focusMobileGroup(PUBLIC_NAV_GROUPS.length-1)}}} className={`min-h-12 rounded-xl px-2 text-xs font-bold transition motion-reduce:transition-none ${mobileGroup===group.label?"bg-white text-brand-dark shadow-e1":"text-text-muted hover:text-brand-dark"}`}>{group.label}</button>)}</div>{PUBLIC_NAV_GROUPS.map((group,index)=><section key={group.label} id={`mobile-nav-panel-${index}`} role="tabpanel" aria-labelledby={`mobile-nav-tab-${index}`} hidden={mobileGroup!==group.label} className="mt-4"><ul className="space-y-1">{group.items.map(item=><li key={item.path}><NavLink to={item.path} className={({isActive})=>`block min-h-12 rounded-xl px-3 py-3 font-semibold ${isActive?"bg-brand-dark text-white":"text-text-main hover:bg-bg-soft"}`}>{item.label}<span className={`mt-1 block text-xs font-normal leading-5 ${location.pathname===item.path||location.pathname.startsWith(`${item.path}/`)?"text-white/70":"text-text-muted"}`}>{item.description}</span></NavLink></li>)}</ul></section>)}</nav><div className="mt-5 grid grid-cols-2 gap-2 border-t border-brand-dark/10 pt-5"><Link to="/iniciar-sesion" className="public-button-secondary">Ingresar</Link><Link to="/comenzar" className="public-button-primary">Recibir orientación</Link></div><div className="mt-3 grid grid-cols-3 gap-1 text-center text-xs font-semibold"><Link to="/pagos" className="min-h-12 rounded-xl px-2 py-3 text-brand-dark hover:bg-bg-soft">Pagar</Link><Link to="/pqr" className="min-h-12 rounded-xl px-2 py-3 text-brand-dark hover:bg-bg-soft">PQR</Link><Link to="/contacto" className="min-h-12 rounded-xl px-2 py-3 text-brand-dark hover:bg-bg-soft">Contacto</Link></div></Drawer>
    <main id="main-content" ref={mainRef} tabIndex={-1} className="w-full flex-1 focus:outline-none"><RouteTransition routeKey={location.pathname}><Outlet/></RouteTransition></main>
    <footer className="bg-brand-deep text-white"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-14 sm:px-8 md:grid-cols-[1.2fr_2fr] lg:px-12"><div><BrandLogo variant="icon" className="h-14 w-auto"/><p className="mt-5 max-w-sm leading-7 text-white/65">Consulta beneficios, paga o radica solicitudes en línea.</p><p className="mt-5 text-sm text-white/55">{ASODEF_COMPANY.addressLine1} · {ASODEF_COMPANY.city}<br/>{ASODEF_COMPANY.corporateEmail}</p></div><div className="grid gap-8 sm:grid-cols-3">{PUBLIC_NAV_GROUPS.map(group=><nav key={group.label} aria-label={`Pie: ${group.label}`}><p className="text-xs font-bold uppercase tracking-wider text-white/45">{group.label}</p><ul className="mt-4 space-y-3">{group.items.slice(0,5).map(item=><li key={item.path}><Link className="text-sm text-white/75 hover:text-brand-orange-light" to={item.path}>{item.label}</Link></li>)}</ul></nav>)}</div></div><div className="border-t border-white/10"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-5 py-6 text-xs text-white/50 sm:px-8 md:flex-row md:items-center md:justify-between lg:px-12"><p>© {new Date().getFullYear()} {ASODEF_COMPANY.legalName}</p><div className="flex flex-wrap gap-5"><button onClick={openPreferences} className="hover:text-white">Preferencias de cookies</button><Link to="/legal/politica-de-privacidad">Privacidad</Link><Link to="/contacto" className="inline-flex items-center gap-1 hover:text-white"><ShieldCheck aria-hidden="true" className="h-3.5 w-3.5"/>Contacto y atención</Link></div></div></div></footer>
    <WhatsAppFloatingButton phoneNumber={WHATSAPP_NUMBER} tooltip="Escríbenos por WhatsApp" ariaLabel="Contactar por WhatsApp (se abre en una pestaña nueva)"/>
  </div>;
}
