import { useEffect, useRef, useState } from "react";
import { Link, NavLink, Outlet, useLocation } from "react-router-dom";
import { ASODEF_COMPANY } from "@asodef/config";
import { Drawer, IconButton } from "@asodef/ui";
import { ArrowRight, ChevronDown, CreditCard, LogIn, Menu, ShieldCheck } from "lucide-react";
import { PUBLIC_NAV_GROUPS, PUBLIC_ROUTES } from "../lib/public-content/public-routes";
import { useCookieConsent } from "../lib/cookie-consent/cookie-consent-context";
import { BrandLogo } from "./shared/BrandLogo";
import { SkipToContent } from "./shared/SkipToContent";
import { useFocusMainOnRouteChange } from "./shared/useFocusMainOnRouteChange";
import { useScrollToHash } from "./shared/useScrollToHash";
import { WhatsAppFloatingButton } from "./shared/WhatsAppFloatingButton";
import { RouteTransition } from "../components/public/motion";

const WHATSAPP_NUMBER = "573232733927";
const primary = [PUBLIC_ROUTES.about, PUBLIC_ROUTES.benefits, PUBLIC_ROUTES.solutions, PUBLIC_ROUTES.companies];
const resourceItems = [PUBLIC_ROUTES.pqr, PUBLIC_ROUTES.dsr];

export function PublicLayout() {
  const mainRef = useRef<HTMLElement>(null);
  const menuRef = useRef<HTMLLIElement>(null);
  const hamburgerRef = useRef<HTMLButtonElement>(null);
  const location = useLocation();
  const { openPreferences } = useCookieConsent();
  const [scrolled, setScrolled] = useState(false);
  const [drawerOpen, setDrawerOpen] = useState(false);
  const [resourcesOpen, setResourcesOpen] = useState(false);
  useFocusMainOnRouteChange(mainRef); useScrollToHash();

  useEffect(() => { const onScroll=()=>setScrolled(window.scrollY>8); onScroll(); window.addEventListener("scroll",onScroll,{passive:true}); return()=>window.removeEventListener("scroll",onScroll); },[]);
  useEffect(()=>{setDrawerOpen(false);setResourcesOpen(false);},[location.pathname,location.hash]);
  useEffect(()=>{ if(!resourcesOpen)return; const onDown=(e:MouseEvent)=>{if(!menuRef.current?.contains(e.target as Node))setResourcesOpen(false)}; const onKey=(e:KeyboardEvent)=>{if(e.key==="Escape")setResourcesOpen(false)}; document.addEventListener("mousedown",onDown);document.addEventListener("keydown",onKey);return()=>{document.removeEventListener("mousedown",onDown);document.removeEventListener("keydown",onKey)};},[resourcesOpen]);
  const closeDrawer=()=>{setDrawerOpen(false);requestAnimationFrame(()=>hamburgerRef.current?.focus())};
  return <div className="flex min-h-screen flex-col overflow-x-clip bg-bg-base"><SkipToContent targetId="main-content"/>
    <header className={`sticky top-0 z-40 border-b transition ${scrolled?"border-brand-dark/10 bg-[#F4F5F1]/92 shadow-e2 backdrop-blur-2xl":"border-transparent bg-bg-base/80 backdrop-blur-xl"}`}><div className="mx-auto flex max-w-7xl items-center gap-5 px-5 py-3 sm:px-8 lg:px-12"><Link to="/" aria-label={`${ASODEF_COMPANY.legalName}, inicio`}><BrandLogo className="h-10 w-auto"/></Link>
      <nav aria-label="Principal" className="ml-auto hidden items-center lg:flex"><ul className="flex items-center gap-1"><li><NavLink to="/" end className={({isActive})=>`rounded-full px-3 py-2 text-sm font-semibold ${isActive?"bg-brand-dark/8 text-brand-dark":"text-text-muted hover:text-brand-dark"}`}>Inicio</NavLink></li>{primary.map(item=><li key={item.path}><NavLink to={item.path} className={({isActive})=>`rounded-full px-3 py-2 text-sm font-semibold ${isActive?"bg-brand-dark/8 text-brand-dark":"text-text-muted hover:text-brand-dark"}`}>{item.label}</NavLink></li>)}<li ref={menuRef} className="relative"><button aria-expanded={resourcesOpen} aria-controls="resource-menu" onClick={()=>setResourcesOpen(v=>!v)} className="flex min-h-10 items-center gap-1 rounded-full px-3 py-2 text-sm font-semibold text-text-muted hover:text-brand-dark focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-orange focus-visible:ring-offset-2">Recursos<ChevronDown className={`h-4 w-4 transition motion-reduce:transition-none ${resourcesOpen?"rotate-180":""}`}/></button>{resourcesOpen&&<div id="resource-menu" className="absolute right-0 top-12 w-[28rem] rounded-3xl border border-brand-dark/10 bg-white p-3 shadow-e4"><div className="grid grid-cols-2 gap-2">{resourceItems.map(item=><Link key={item.path} to={item.path} className="min-h-24 rounded-2xl p-4 hover:bg-bg-soft focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-orange"><span className="font-semibold text-brand-dark">{item.label}</span><span className="mt-1 block text-xs leading-5 text-text-muted">{item.description}</span></Link>)}</div></div>}</li></ul></nav>
      <div className="hidden items-center gap-2 lg:flex"><Link to="/pagos" className="inline-flex min-h-10 items-center justify-center gap-2 rounded-full bg-brand-orange px-4 text-sm font-bold text-brand-deep shadow-e1 transition hover:-translate-y-0.5 hover:shadow-e2 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-orange focus-visible:ring-offset-2 motion-reduce:transform-none motion-reduce:transition-none"><CreditCard className="h-4 w-4"/>Pagar</Link><Link to="/iniciar-sesion" className="public-button-secondary !min-h-10 !px-4"><LogIn className="h-4 w-4"/>Ingresar</Link><Link to="/comenzar" className="public-button-primary !min-h-10 !px-4">Recibir orientación<ArrowRight className="h-4 w-4"/></Link></div>
      <IconButton ref={hamburgerRef} aria-label="Abrir menú de navegación" icon={<Menu className="h-5 w-5"/>} className="ml-auto !h-12 !w-12 lg:hidden" onClick={()=>setDrawerOpen(true)}/></div></header>
    <Drawer open={drawerOpen} onClose={closeDrawer} title="Navegación" description="Accesos públicos de ASODEF" side="right" className="max-w-[24rem]"><div className="mb-5 border-b border-brand-dark/10 pb-5"><BrandLogo className="h-9 w-auto"/></div><nav aria-label="Principal móvil"><p className="text-xs font-bold uppercase tracking-[.14em] text-text-muted">Conocer ASODEF</p><ul className="mt-2 grid gap-1">{primary.map(item=><li key={item.path}><NavLink to={item.path} className={({isActive})=>`flex min-h-12 items-center rounded-xl px-3 py-2 text-sm font-semibold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-orange ${isActive?"bg-brand-dark text-white":"text-text-main hover:bg-bg-soft"}`}>{item.label}</NavLink></li>)}</ul><div className="my-5 border-t border-brand-dark/10"/><p className="text-xs font-bold uppercase tracking-[.14em] text-text-muted">Recursos</p><ul className="mt-2 grid grid-cols-2 gap-2">{resourceItems.map(item=><li key={item.path}><NavLink to={item.path} className={({isActive})=>`flex min-h-14 items-center rounded-xl px-3 py-2 text-sm font-semibold leading-tight focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-orange ${isActive?"bg-brand-dark text-white":"bg-bg-soft text-brand-dark hover:bg-brand-dark/10"}`}>{item.label}</NavLink></li>)}</ul></nav><div aria-label="Acciones principales" className="mt-5 grid gap-2 border-t border-brand-dark/10 pt-5"><Link to="/pagos" className="inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-brand-orange px-4 text-sm font-bold text-brand-deep shadow-e1 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-orange focus-visible:ring-offset-2"><CreditCard className="h-4 w-4"/>Pagar</Link><Link to="/iniciar-sesion" className="public-button-secondary w-full justify-center"><LogIn className="h-4 w-4"/>Ingresar</Link><Link to="/comenzar" className="public-button-primary w-full justify-center">Recibir orientación<ArrowRight className="h-4 w-4"/></Link></div></Drawer>
    <main id="main-content" ref={mainRef} tabIndex={-1} className="w-full flex-1 focus:outline-none"><RouteTransition routeKey={location.pathname}><Outlet/></RouteTransition></main>
    <footer className="bg-brand-deep text-white"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-14 sm:px-8 md:grid-cols-[1.2fr_2fr] lg:px-12"><div><BrandLogo variant="icon" className="h-14 w-auto"/><p className="mt-5 max-w-sm leading-7 text-white/65">Consulta beneficios, paga o radica solicitudes en línea.</p><p className="mt-5 text-sm text-white/55">{ASODEF_COMPANY.addressLine1} · {ASODEF_COMPANY.city}<br/>{ASODEF_COMPANY.corporateEmail}</p></div><div className="grid gap-8 sm:grid-cols-3">{PUBLIC_NAV_GROUPS.map(group=><nav key={group.label} aria-label={`Pie: ${group.label}`}><p className="text-xs font-bold uppercase tracking-wider text-white/45">{group.label}</p><ul className="mt-4 space-y-3">{group.items.slice(0,5).map(item=><li key={item.path}><Link className="text-sm text-white/75 hover:text-brand-orange-light" to={item.path}>{item.label}</Link></li>)}</ul></nav>)}</div></div><div className="border-t border-white/10"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-5 py-6 text-xs text-white/50 sm:px-8 md:flex-row md:items-center md:justify-between lg:px-12"><p>© {new Date().getFullYear()} {ASODEF_COMPANY.legalName}</p><div className="flex flex-wrap gap-5"><button onClick={openPreferences} className="hover:text-white">Preferencias de cookies</button><Link to="/legal/politica-de-privacidad">Privacidad</Link><Link to="/contacto" className="inline-flex items-center gap-1 hover:text-white"><ShieldCheck aria-hidden="true" className="h-3.5 w-3.5"/>Contacto y atención</Link></div></div></div></footer>
    <WhatsAppFloatingButton phoneNumber={WHATSAPP_NUMBER} tooltip="Escríbenos por WhatsApp" ariaLabel="Contactar por WhatsApp (se abre en una pestaña nueva)"/>
  </div>;
}
